package voxgig.solardemosdk.core

import java.util.{Map => JMap}

import voxgig.solardemosdk.utility.Json

// Static SDK configuration and by-name feature construction.
object Config {

  def makeConfig(): JMap[String, Object] =
    Json.parse(configJson()).asInstanceOf[JMap[String, Object]]

  // SHARED CONFIG (sdkgen rung L2).
  //
  // The SDK reads the config on every request and never writes to it, so one
  // instance is shared by every client rather than rebuilt per client - the
  // difference between parsing the embedded JSON once and once per client.
  //
  // A lazy val is initialised once, on first use, under a lock, so
  // concurrent first calls build it exactly once.
  //
  // The returned map is SHARED: treat it as read-only. Callers that need to
  // mutate should use makeConfig, which always parses a fresh copy.
  private lazy val sharedConfigVal: JMap[String, Object] = makeConfig()

  def sharedConfig(): JMap[String, Object] = sharedConfigVal

  def makeFeature(name: String): Feature = name match {
    case "test" => new voxgig.solardemosdk.feature.TestFeature()
    case _ => new voxgig.solardemosdk.feature.BaseFeature()
  }

  private def configJson(): String = {
    val b = new StringBuilder()
    b.append("{")
    b.append(" \"main\": {")
    b.append("  \"name\": \"Solardemo\"")
    b.append(" },")
    b.append(" \"feature\": {")
    b.append("  \"test\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   }")
    b.append("  }")
    b.append(" },")
    b.append(" \"options\": {")
    b.append("  \"base\": \"http://localhost:8901\",")
    b.append("  \"headers\": {")
    b.append("   \"content-type\": \"application/json\"")
    b.append("  },")
    b.append("  \"entity\": {")
    b.append("   \"moon\": {},")
    b.append("   \"planet\": {}")
    b.append("  }")
    b.append(" },")
    b.append(" \"entity\": {")
    b.append("  \"moon\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"diameter\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$NUMBER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"id\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"kind\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"name\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"planet_id\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"moon\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"planet_id\",")
    b.append("          \"orig\": \"planet_id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/api/planet/{planet_id}/moon\",")
    b.append("       \"parts\": [")
    b.append("        \"api\",")
    b.append("        \"planet\",")
    b.append("        \"{planet_id}\",")
    b.append("        \"moon\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"planet_id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"list\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"list\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"planet_id\",")
    b.append("          \"orig\": \"planet_id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/api/planet/{planet_id}/moon\",")
    b.append("       \"parts\": [")
    b.append("        \"api\",")
    b.append("        \"planet\",")
    b.append("        \"{planet_id}\",")
    b.append("        \"moon\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"planet_id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"moon_id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"planet_id\",")
    b.append("          \"orig\": \"planet_id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/api/planet/{planet_id}/moon/{moon_id}\",")
    b.append("       \"parts\": [")
    b.append("        \"api\",")
    b.append("        \"planet\",")
    b.append("        \"{planet_id}\",")
    b.append("        \"moon\",")
    b.append("        \"{id}\"")
    b.append("       ],")
    b.append("       \"rename\": {")
    b.append("        \"param\": {")
    b.append("         \"moon_id\": \"id\"")
    b.append("        }")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"id\",")
    b.append("         \"planet_id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"remove\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"remove\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"moon_id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"planet_id\",")
    b.append("          \"orig\": \"planet_id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"DELETE\",")
    b.append("       \"orig\": \"/api/planet/{planet_id}/moon/{moon_id}\",")
    b.append("       \"parts\": [")
    b.append("        \"api\",")
    b.append("        \"planet\",")
    b.append("        \"{planet_id}\",")
    b.append("        \"moon\",")
    b.append("        \"{id}\"")
    b.append("       ],")
    b.append("       \"rename\": {")
    b.append("        \"param\": {")
    b.append("         \"moon_id\": \"id\"")
    b.append("        }")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"id\",")
    b.append("         \"planet_id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"update\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"update\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"moon_id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"planet_id\",")
    b.append("          \"orig\": \"planet_id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"PUT\",")
    b.append("       \"orig\": \"/api/planet/{planet_id}/moon/{moon_id}\",")
    b.append("       \"parts\": [")
    b.append("        \"api\",")
    b.append("        \"planet\",")
    b.append("        \"{planet_id}\",")
    b.append("        \"moon\",")
    b.append("        \"{id}\"")
    b.append("       ],")
    b.append("       \"rename\": {")
    b.append("        \"param\": {")
    b.append("         \"moon_id\": \"id\"")
    b.append("        }")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"id\",")
    b.append("         \"planet_id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": [")
    b.append("     [")
    b.append("      \"planet\"")
    b.append("     ]")
    b.append("    ]")
    b.append("   }")
    b.append("  },")
    b.append("  \"planet\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"diameter\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$NUMBER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"forbid\",")
    b.append("     \"type\": \"`$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"id\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"kind\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"name\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"ok\",")
    b.append("     \"type\": \"`$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"start\",")
    b.append("     \"type\": \"`$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"state\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"stop\",")
    b.append("     \"type\": \"`$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"why\",")
    b.append("     \"type\": \"`$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"planet\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"planet_id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/api/planet/{planet_id}/forbid\",")
    b.append("       \"parts\": [")
    b.append("        \"api\",")
    b.append("        \"planet\",")
    b.append("        \"{id}\",")
    b.append("        \"forbid\"")
    b.append("       ],")
    b.append("       \"rename\": {")
    b.append("        \"param\": {")
    b.append("         \"planet_id\": \"id\"")
    b.append("        }")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"$action\": \"forbid\",")
    b.append("        \"exist\": [")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"planet_id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/api/planet/{planet_id}/terraform\",")
    b.append("       \"parts\": [")
    b.append("        \"api\",")
    b.append("        \"planet\",")
    b.append("        \"{id}\",")
    b.append("        \"terraform\"")
    b.append("       ],")
    b.append("       \"rename\": {")
    b.append("        \"param\": {")
    b.append("         \"planet_id\": \"id\"")
    b.append("        }")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"$action\": \"terraform\",")
    b.append("        \"exist\": [")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/api/planet\",")
    b.append("       \"parts\": [")
    b.append("        \"api\",")
    b.append("        \"planet\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"list\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"list\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/api/planet\",")
    b.append("       \"parts\": [")
    b.append("        \"api\",")
    b.append("        \"planet\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"planet_id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/api/planet/{planet_id}\",")
    b.append("       \"parts\": [")
    b.append("        \"api\",")
    b.append("        \"planet\",")
    b.append("        \"{id}\"")
    b.append("       ],")
    b.append("       \"rename\": {")
    b.append("        \"param\": {")
    b.append("         \"planet_id\": \"id\"")
    b.append("        }")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"remove\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"remove\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"planet_id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"DELETE\",")
    b.append("       \"orig\": \"/api/planet/{planet_id}\",")
    b.append("       \"parts\": [")
    b.append("        \"api\",")
    b.append("        \"planet\",")
    b.append("        \"{id}\"")
    b.append("       ],")
    b.append("       \"rename\": {")
    b.append("        \"param\": {")
    b.append("         \"planet_id\": \"id\"")
    b.append("        }")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"update\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"update\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"planet_id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"PUT\",")
    b.append("       \"orig\": \"/api/planet/{planet_id}\",")
    b.append("       \"parts\": [")
    b.append("        \"api\",")
    b.append("        \"planet\",")
    b.append("        \"{id}\"")
    b.append("       ],")
    b.append("       \"rename\": {")
    b.append("        \"param\": {")
    b.append("         \"planet_id\": \"id\"")
    b.append("        }")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  }")
    b.append(" }")
    b.append("}")
    b.toString
  }
}
