# Solardemo SDK deployment. GENERATED by @voxgig/sdkgen — regenerated
# on every `npm run generate` in .sdk/; publication details live in the
# model (.sdk/model/target/<target>.aon, `publish` section).
#
# Every port gets a git release tag <target>/vX.Y.Z. Ports with an ACTIVE
# registry also publish a package there. Credentials are injected at exec
# time by the boru key vault (https://github.com/boru-lang/boru) — never
# stored on disk or passed on the command line.
#
# Publication state (from the model):
#   c        none (publish pending: deploy publishes the git tag only)
#   clojure  clojars (publish pending: deploy publishes the git tag only) https://clojars.org
#   cpp      none (publish pending: deploy publishes the git tag only)
#   csharp   nuget (publish pending: deploy publishes the git tag only) https://www.nuget.org
#   dart     pub.dev (publish pending: deploy publishes the git tag only) https://pub.dev
#   elixir   hex (publish pending: deploy publishes the git tag only) https://hex.pm
#   go       tag-only
#   go-cli   tag-only
#   go-mcp   tag-only
#   java     maven-central (publish pending: deploy publishes the git tag only) https://central.sonatype.com
#   js       npm (publish pending: deploy publishes the git tag only) https://registry.npmjs.org
#   kotlin   maven-central (publish pending: deploy publishes the git tag only) https://central.sonatype.com
#   lean     reservoir (publish pending: deploy publishes the git tag only) https://reservoir.lean-lang.org
#   lua      luarocks (publish pending: deploy publishes the git tag only) https://luarocks.org
#   ocaml    opam (publish pending: deploy publishes the git tag only) https://opam.ocaml.org
#   perl     cpan (publish pending: deploy publishes the git tag only) https://www.cpan.org
#   php      packagist (publish pending: deploy publishes the git tag only) https://packagist.org
#   py       pypi (publish pending: deploy publishes the git tag only) https://pypi.org
#   py-data  pypi (publish pending: deploy publishes the git tag only) https://pypi.org
#   rb       rubygems (publish pending: deploy publishes the git tag only) https://rubygems.org
#   rust     crates.io (publish pending: deploy publishes the git tag only) https://crates.io
#   scala    maven-central (publish pending: deploy publishes the git tag only) https://central.sonatype.com
#   seneca-provider npm (publish pending: deploy publishes the git tag only) https://registry.npmjs.org
#   swift    swiftpm (publish pending: deploy publishes the git tag only) https://swift.org/package-manager
#   ts       npm (publish pending: deploy publishes the git tag only) https://registry.npmjs.org
#   zig      none (publish pending: deploy publishes the git tag only)
#
#   make deploy               list per-target deploy commands
#   make deploy-<target>      deploy ONE target (no deploy-all: each
#                             registry upload is irreversible); while a
#                             registry is pending this publishes the
#                             port's git tag only
#   make deploy-dry           rehearse EVERY target: boru --dry-run
#                             injects a filler token that each publish
#                             recipe detects, so build + test run in full
#                             but nothing is uploaded and no tag is cut
#
# Vault aliases (override per invocation, e.g. make deploy-ts NPM_ALIAS=work:npm):

SHELL := /bin/bash

GITHUB_ALIAS ?= github
NONE_ALIAS ?= none
CLOJARS_ALIAS ?= clojars
NUGET_ALIAS ?= nuget
PUB_DEV_ALIAS ?= pubdev
HEX_ALIAS ?= hex
MAVEN_CENTRAL_ALIAS ?= central
NPM_ALIAS ?= npm
RESERVOIR_ALIAS ?= reservoir
LUAROCKS_ALIAS ?= luarocks
OPAM_ALIAS ?= opam
CPAN_ALIAS ?= cpan
PACKAGIST_ALIAS ?= packagist
PYPI_ALIAS ?= pypi
RUBYGEMS_ALIAS ?= gem
CRATES_IO_ALIAS ?= cratesio
SWIFTPM_ALIAS ?= swiftpm

# Lockstep SDK version, read from the canonical ts manifest.
VERSION := $(shell node -p "require('./ts/package.json').version" 2>/dev/null || echo 0.0.0)
BORU_DRY_RUN_FILLER := BORU-DRY-RUN-FILLER-NOT-A-REAL-SECRET

TARGETS := c clojure cpp csharp dart elixir go go-cli go-mcp java js kotlin lean lua ocaml perl php py py-data rb rust scala seneca-provider swift ts zig

.PHONY: deploy deploy-dry \
  $(addprefix deploy-,$(TARGETS)) $(addprefix deploy-dry-,$(TARGETS)) \
  $(addprefix tag-push-,$(TARGETS))

deploy:
	@echo "Deployment is per-target — pick one (each upload is irreversible):"
	@echo "  make deploy-<target>    targets: $(TARGETS)"
	@echo "Registry state is set in the model (.sdk/model/target/<t>.aon):"
	@echo "  deploy-c        none publish pending (deploy = git tag only)"
	@echo "  deploy-clojure  clojars publish pending (deploy = git tag only)"
	@echo "  deploy-cpp      none publish pending (deploy = git tag only)"
	@echo "  deploy-csharp   nuget publish pending (deploy = git tag only)"
	@echo "  deploy-dart     pub.dev publish pending (deploy = git tag only)"
	@echo "  deploy-elixir   hex publish pending (deploy = git tag only)"
	@echo "  deploy-go       tag-only"
	@echo "  deploy-go-cli   tag-only"
	@echo "  deploy-go-mcp   tag-only"
	@echo "  deploy-java     maven-central publish pending (deploy = git tag only)"
	@echo "  deploy-js       npm publish pending (deploy = git tag only)"
	@echo "  deploy-kotlin   maven-central publish pending (deploy = git tag only)"
	@echo "  deploy-lean     reservoir publish pending (deploy = git tag only)"
	@echo "  deploy-lua      luarocks publish pending (deploy = git tag only)"
	@echo "  deploy-ocaml    opam publish pending (deploy = git tag only)"
	@echo "  deploy-perl     cpan publish pending (deploy = git tag only)"
	@echo "  deploy-php      packagist publish pending (deploy = git tag only)"
	@echo "  deploy-py       pypi publish pending (deploy = git tag only)"
	@echo "  deploy-py-data  pypi publish pending (deploy = git tag only)"
	@echo "  deploy-rb       rubygems publish pending (deploy = git tag only)"
	@echo "  deploy-rust     crates.io publish pending (deploy = git tag only)"
	@echo "  deploy-scala    maven-central publish pending (deploy = git tag only)"
	@echo "  deploy-seneca-provider npm publish pending (deploy = git tag only)"
	@echo "  deploy-swift    swiftpm publish pending (deploy = git tag only)"
	@echo "  deploy-ts       npm publish pending (deploy = git tag only)"
	@echo "  deploy-zig      none publish pending (deploy = git tag only)"
	@echo "Rehearse everything safely first: make deploy-dry"

deploy-dry: $(addprefix deploy-dry-,$(TARGETS))
	@echo "deploy-dry: all targets rehearsed OK ($(TARGETS))"

deploy-c:
	@echo "deploy-c: none publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-c

deploy-dry-c:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-c

tag-push-c:
	@set -e; tag="c/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-c: no GITHUB_TOKEN in env — run via make deploy-c (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (none publication pending — tag-only deploy)"

deploy-clojure:
	@echo "deploy-clojure: clojars publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-clojure

deploy-dry-clojure:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-clojure

tag-push-clojure:
	@set -e; tag="clojure/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-clojure: no GITHUB_TOKEN in env — run via make deploy-clojure (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (clojars publication pending — tag-only deploy)"

deploy-cpp:
	@echo "deploy-cpp: none publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-cpp

deploy-dry-cpp:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-cpp

tag-push-cpp:
	@set -e; tag="cpp/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-cpp: no GITHUB_TOKEN in env — run via make deploy-cpp (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (none publication pending — tag-only deploy)"

deploy-csharp:
	@echo "deploy-csharp: nuget publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-csharp

deploy-dry-csharp:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-csharp

tag-push-csharp:
	@set -e; tag="csharp/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-csharp: no GITHUB_TOKEN in env — run via make deploy-csharp (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (nuget publication pending — tag-only deploy)"

deploy-dart:
	@echo "deploy-dart: pub.dev publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-dart

deploy-dry-dart:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-dart

tag-push-dart:
	@set -e; tag="dart/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-dart: no GITHUB_TOKEN in env — run via make deploy-dart (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (pub.dev publication pending — tag-only deploy)"

deploy-elixir:
	@echo "deploy-elixir: hex publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-elixir

deploy-dry-elixir:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-elixir

tag-push-elixir:
	@set -e; tag="elixir/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-elixir: no GITHUB_TOKEN in env — run via make deploy-elixir (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (hex publication pending — tag-only deploy)"

deploy-go:
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) -C go publish

deploy-dry-go:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) -C go publish

deploy-go-cli:
	@echo "deploy-go-cli: tag-only port — publishing the git tag."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-go-cli

deploy-dry-go-cli:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-go-cli

tag-push-go-cli:
	@set -e; tag="go-cli/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-go-cli: no GITHUB_TOKEN in env — run via make deploy-go-cli (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (tag-only port)"

deploy-go-mcp:
	@echo "deploy-go-mcp: tag-only port — publishing the git tag."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-go-mcp

deploy-dry-go-mcp:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-go-mcp

tag-push-go-mcp:
	@set -e; tag="go-mcp/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-go-mcp: no GITHUB_TOKEN in env — run via make deploy-go-mcp (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (tag-only port)"

deploy-java:
	@echo "deploy-java: maven-central publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-java

deploy-dry-java:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-java

tag-push-java:
	@set -e; tag="java/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-java: no GITHUB_TOKEN in env — run via make deploy-java (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (maven-central publication pending — tag-only deploy)"

deploy-js:
	@echo "deploy-js: npm publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-js

deploy-dry-js:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-js

tag-push-js:
	@set -e; tag="js/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-js: no GITHUB_TOKEN in env — run via make deploy-js (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (npm publication pending — tag-only deploy)"

deploy-kotlin:
	@echo "deploy-kotlin: maven-central publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-kotlin

deploy-dry-kotlin:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-kotlin

tag-push-kotlin:
	@set -e; tag="kotlin/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-kotlin: no GITHUB_TOKEN in env — run via make deploy-kotlin (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (maven-central publication pending — tag-only deploy)"

deploy-lean:
	@echo "deploy-lean: reservoir publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-lean

deploy-dry-lean:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-lean

tag-push-lean:
	@set -e; tag="lean/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-lean: no GITHUB_TOKEN in env — run via make deploy-lean (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (reservoir publication pending — tag-only deploy)"

deploy-lua:
	@echo "deploy-lua: luarocks publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-lua

deploy-dry-lua:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-lua

tag-push-lua:
	@set -e; tag="lua/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-lua: no GITHUB_TOKEN in env — run via make deploy-lua (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (luarocks publication pending — tag-only deploy)"

deploy-ocaml:
	@echo "deploy-ocaml: opam publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-ocaml

deploy-dry-ocaml:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-ocaml

tag-push-ocaml:
	@set -e; tag="ocaml/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-ocaml: no GITHUB_TOKEN in env — run via make deploy-ocaml (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (opam publication pending — tag-only deploy)"

deploy-perl:
	@echo "deploy-perl: cpan publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-perl

deploy-dry-perl:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-perl

tag-push-perl:
	@set -e; tag="perl/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-perl: no GITHUB_TOKEN in env — run via make deploy-perl (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (cpan publication pending — tag-only deploy)"

deploy-php:
	@echo "deploy-php: packagist publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-php

deploy-dry-php:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-php

tag-push-php:
	@set -e; tag="php/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-php: no GITHUB_TOKEN in env — run via make deploy-php (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (packagist publication pending — tag-only deploy)"

deploy-py:
	@echo "deploy-py: pypi publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-py

deploy-dry-py:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-py

tag-push-py:
	@set -e; tag="py/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-py: no GITHUB_TOKEN in env — run via make deploy-py (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (pypi publication pending — tag-only deploy)"

deploy-py-data:
	@echo "deploy-py-data: pypi publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-py-data

deploy-dry-py-data:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-py-data

tag-push-py-data:
	@set -e; tag="py-data/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-py-data: no GITHUB_TOKEN in env — run via make deploy-py-data (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (pypi publication pending — tag-only deploy)"

deploy-rb:
	@echo "deploy-rb: rubygems publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-rb

deploy-dry-rb:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-rb

tag-push-rb:
	@set -e; tag="rb/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-rb: no GITHUB_TOKEN in env — run via make deploy-rb (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (rubygems publication pending — tag-only deploy)"

deploy-rust:
	@echo "deploy-rust: crates.io publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-rust

deploy-dry-rust:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-rust

tag-push-rust:
	@set -e; tag="rust/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-rust: no GITHUB_TOKEN in env — run via make deploy-rust (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (crates.io publication pending — tag-only deploy)"

deploy-scala:
	@echo "deploy-scala: maven-central publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-scala

deploy-dry-scala:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-scala

tag-push-scala:
	@set -e; tag="scala/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-scala: no GITHUB_TOKEN in env — run via make deploy-scala (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (maven-central publication pending — tag-only deploy)"

deploy-seneca-provider:
	@echo "deploy-seneca-provider: npm publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-seneca-provider

deploy-dry-seneca-provider:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-seneca-provider

tag-push-seneca-provider:
	@set -e; tag="seneca-provider/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-seneca-provider: no GITHUB_TOKEN in env — run via make deploy-seneca-provider (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (npm publication pending — tag-only deploy)"

deploy-swift:
	@echo "deploy-swift: swiftpm publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-swift

deploy-dry-swift:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-swift

tag-push-swift:
	@set -e; tag="swift/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-swift: no GITHUB_TOKEN in env — run via make deploy-swift (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (swiftpm publication pending — tag-only deploy)"

deploy-ts:
	@echo "deploy-ts: npm publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-ts

deploy-dry-ts:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-ts

tag-push-ts:
	@set -e; tag="ts/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-ts: no GITHUB_TOKEN in env — run via make deploy-ts (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (npm publication pending — tag-only deploy)"

deploy-zig:
	@echo "deploy-zig: none publication is pending — publishing the git tag only."
	boru vault exec --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-zig

deploy-dry-zig:
	boru vault exec --dry-run --for=github=$(GITHUB_ALIAS) -- $(MAKE) tag-push-zig

tag-push-zig:
	@set -e; tag="zig/v$(VERSION)"; \
	token="$${GITHUB_TOKEN:-$$GH_TOKEN}"; \
	if [ "$$token" = "$(BORU_DRY_RUN_FILLER)" ]; then \
	  echo "[dry-run] boru filler token detected: would create (if missing) and push tag $$tag; nothing pushed."; exit 0; fi; \
	if [ -z "$$token" ]; then echo "tag-push-zig: no GITHUB_TOKEN in env — run via make deploy-zig (boru vault exec)"; exit 1; fi; \
	if git rev-parse -q --verify "refs/tags/$$tag" >/dev/null; then \
	  echo "tag $$tag already exists — pushing existing tag"; \
	else git tag -a "$$tag" -m "Release $$tag"; fi; \
	url=$$(git remote get-url origin | sed -E 's#^git@github.com:#https://github.com/#'); \
	hdr="AUTHORIZATION: basic $$(printf 'x-access-token:%s' "$$token" | base64 | tr -d '\n')"; \
	git -c http.extraheader="$$hdr" push "$$url" "$$tag"; \
	echo "pushed $$tag (none publication pending — tag-only deploy)"
