name: solardemo_sdk
description: >-
  Unofficial generated dart SDK for the Solar System public API. Not affiliated with or endorsed by the upstream API provider.
version: 0.1.0
homepage: https://github.com/voxgig-sdk/solardemo-sdk
repository: https://github.com/voxgig-sdk/solardemo-sdk
issue_tracker: https://github.com/voxgig-sdk/solardemo-sdk/issues
topics:
  - voxgig
  - sdk
  - generated-sdk
  - openapi
  - api-client
environment:
  sdk: '>=3.0.0 <4.0.0'
