<?php
declare(strict_types=1);

// VoxgigSolardemo SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

VoxgigSolardemoUtility::setRegistrar(function (VoxgigSolardemoUtility $u): void {
    $u->clean = [VoxgigSolardemoClean::class, 'call'];
    $u->done = [VoxgigSolardemoDone::class, 'call'];
    $u->make_error = [VoxgigSolardemoMakeError::class, 'call'];
    $u->feature_add = [VoxgigSolardemoFeatureAdd::class, 'call'];
    $u->feature_hook = [VoxgigSolardemoFeatureHook::class, 'call'];
    $u->feature_init = [VoxgigSolardemoFeatureInit::class, 'call'];
    $u->fetcher = [VoxgigSolardemoFetcher::class, 'call'];
    $u->make_fetch_def = [VoxgigSolardemoMakeFetchDef::class, 'call'];
    $u->make_context = [VoxgigSolardemoMakeContext::class, 'call'];
    $u->make_options = [VoxgigSolardemoMakeOptions::class, 'call'];
    $u->make_request = [VoxgigSolardemoMakeRequest::class, 'call'];
    $u->make_response = [VoxgigSolardemoMakeResponse::class, 'call'];
    $u->make_result = [VoxgigSolardemoMakeResult::class, 'call'];
    $u->make_point = [VoxgigSolardemoMakePoint::class, 'call'];
    $u->make_spec = [VoxgigSolardemoMakeSpec::class, 'call'];
    $u->make_url = [VoxgigSolardemoMakeUrl::class, 'call'];
    $u->param = [VoxgigSolardemoParam::class, 'call'];
    $u->prepare_auth = [VoxgigSolardemoPrepareAuth::class, 'call'];
    $u->prepare_body = [VoxgigSolardemoPrepareBody::class, 'call'];
    $u->prepare_headers = [VoxgigSolardemoPrepareHeaders::class, 'call'];
    $u->prepare_method = [VoxgigSolardemoPrepareMethod::class, 'call'];
    $u->prepare_params = [VoxgigSolardemoPrepareParams::class, 'call'];
    $u->prepare_path = [VoxgigSolardemoPreparePath::class, 'call'];
    $u->prepare_query = [VoxgigSolardemoPrepareQuery::class, 'call'];
    $u->graphql_body = [VoxgigSolardemoGraphql::class, 'body'];
    $u->graphql_errors = [VoxgigSolardemoGraphql::class, 'errors'];
    $u->result_basic = [VoxgigSolardemoResultBasic::class, 'call'];
    $u->result_body = [VoxgigSolardemoResultBody::class, 'call'];
    $u->result_headers = [VoxgigSolardemoResultHeaders::class, 'call'];
    $u->transform_request = [VoxgigSolardemoTransformRequest::class, 'call'];
    $u->transform_response = [VoxgigSolardemoTransformResponse::class, 'call'];
});
