-- Solardemo SDK public client (generated by @voxgig/sdkgen).
--
-- Constructors (newSdk / testSdk) and one op namespace per entity. Entities are
-- generic: every op delegates to the config-driven SdkRuntime, so the pipeline
-- is identical for every entity and every API.

import VoxgigStruct
import SdkRuntime
import SdkConfig

open VoxgigStruct

namespace Sdk

/-- Construct a live client from an options map (empty map = defaults). -/
def newSdk (options : Value) : SIO Value :=
  SdkRuntime.mkClientV options SdkConfig.configJson

/-- No-argument convenience constructor. -/
def newSdk0 : SIO Value := do newSdk (← emptyMap)

/-- Construct a test-mode client: operations are answered from an in-memory
    store seeded with the entity test data, so no server is needed. -/
def testSdk (seed : Value) (options : Value) : SIO Value :=
  SdkRuntime.mkTestClientV options SdkConfig.configJson seed

/-- Test client with default options. -/
def testSdk0 (seed : Value) : SIO Value := do testSdk seed (← emptyMap)

end Sdk

namespace Moon
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "moon" d co
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "moon" m co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "moon" m co
  def remove (c m co : Value) : SIO Value := SdkRuntime.opRemove c "moon" m co
  def update (c m d co : Value) : SIO Value := SdkRuntime.opUpdate c "moon" m d co
end Moon

namespace Planet
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "planet" d co
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "planet" m co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "planet" m co
  def remove (c m co : Value) : SIO Value := SdkRuntime.opRemove c "planet" m co
  def update (c m d co : Value) : SIO Value := SdkRuntime.opUpdate c "planet" m d co
end Planet

