/* Generated by @voxgig/sdkgen. Do not edit. */
'use strict'

// Seed data for the SDK's offline mock transport, so the entity tests
// exercise real code paths without a server.
const SEED = {
  entity: {
    moon: {
      moon0: {"diameter":100,"id":"moon0","kind":"kind0","name":"name0","planet_id":"planet0"},
      moon1: {"diameter":200,"id":"moon1","kind":"kind1","name":"name1","planet_id":"planet0"},
    },
    planet: {
      planet0: {"diameter":100,"id":"planet0","kind":"kind0","name":"name0"},
      planet1: {"diameter":200,"id":"planet1","kind":"kind1","name":"name1"},
    },
  },
}

module.exports = { SEED }
