/* Generated by @voxgig/sdkgen. Do not edit. */
'use strict'

const { describe, it, before } = require('node:test')
const assert = require('node:assert')

const Seneca = require('seneca')

const SolardemoProvider = require('../dist/solardemo-provider')
const SolardemoProviderDoc = require('../dist/SolardemoProvider-doc')

const SenecaMsgTest = require('seneca-msg-test')
const { Maintain } = require('@seneca/maintain')

const { SEED } = require('./seed')

const BasicMessages = require('../dist-test/basic.messages')

// The live tests run against the companion test server in the SDK repo
// (`app/`), which serves this by default. Start it with:
//   cd ../app && npm start
const LIVE_BASE = process.env.SOLARDEMO_TEST_BASE || 'http://localhost:8901'


describe('solardemo-provider', () => {

  it('happy', async () => {
    assert.notEqual(SolardemoProvider, undefined)
    assert.notEqual(SolardemoProviderDoc, undefined)

    const seneca = await makeSeneca()

    assert.partialDeepStrictEqual(
      await seneca.post('sys:provider,provider:solardemo,get:info'),
      {
        ok: true,
        name: 'solardemo',
      },
    )
  })


  it('messages', async () => {
    const seneca = await makeSeneca()
    await SenecaMsgTest(seneca, BasicMessages)()
  })


  it('sdk-export', async () => {
    const seneca = await makeSeneca()
    const sdk = seneca.export('SolardemoProvider/sdk')()

    assert.equal(typeof sdk.Moon, 'function')
    assert.equal(typeof sdk.Planet, 'function')
  })


  it('planet-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/solardemo/planet').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/solardemo/planet',
    )
  })


  it('planet-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/solardemo/planet')
      .load$('planet0')

    assert.equal(found.id, 'planet0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/solardemo/planet',
    )
  })


  // A 404 from a single-item read is an ordinary "not found" answer, not a
  // failure: the provider turns it into null rather than letting the SDK
  // throw.
  it('planet-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/solardemo/planet')
      .load$('nosuchplanet')

    assert.equal(missing, null)
  })


  it('moon-needs-planet_id', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/solardemo/moon').list$({}),
      /planet_id is required/,
    )
  })


  it('moon-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca
      .entity('provider/solardemo/moon')
      .list$({ planet_id: 'planet0' })

    assert.equal(list.length, 2)
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/solardemo/moon',
    )
    assert.equal(list[0].planet_id, 'planet0')
  })


  it('moon-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/solardemo/moon')
      .load$({ planet_id: 'planet0', id: 'moon0' })

    assert.equal(found.id, 'moon0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/solardemo/moon',
    )
  })


  it('moon-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/solardemo/moon')
      .load$({ planet_id: 'planet0', id: 'nosuchmoon' })

    assert.equal(missing, null)
  })


  it('moon-crud', async () => {
    const seneca = await makeSeneca()
    const ent = seneca.entity('provider/solardemo/moon')

    // Seneca's convention: an entity WITHOUT an id is a create. The API
    // assigns the id itself, so the saved record comes back with one it chose.
    const made = await ent.make$({ planet_id: 'planet0', diameter: 12345, kind: 'crud-kind', name: 'crud-name' }).save$()

    assert.ok(null != made.id)
    assert.equal(
      made.canon$({ string: true }),
      'provider/solardemo/moon',
    )

    const id = made.id

    try {
      const loaded = await ent.load$({ planet_id: 'planet0', id: id })
      assert.equal(loaded.id, id)

      // An entity CARRYING an id is an update, not a second create.
      loaded.kind = 'crud-kind-2'
      const updated = await loaded.save$()

      assert.equal(updated.id, id)
      assert.equal(updated.kind, 'crud-kind-2')

      const reloaded = await ent.load$({ planet_id: 'planet0', id: id })
      assert.equal(reloaded.kind, 'crud-kind-2')
    }
    finally {
      // Always clean up. The mock and the server both hold data for the
      // process lifetime, so a leaked record changes what later tests see.
      await ent.remove$({ planet_id: 'planet0', id: id })
    }

    // remove is real: the record is gone, and reading it is an ordinary
    // not-found rather than an error.
    assert.equal(await ent.load$({ planet_id: 'planet0', id: id }), null)
  })


  it('planet-crud', async () => {
    const seneca = await makeSeneca()
    const ent = seneca.entity('provider/solardemo/planet')

    // Seneca's convention: an entity WITHOUT an id is a create. The API
    // assigns the id itself, so the saved record comes back with one it chose.
    const made = await ent.make$({ diameter: 12345, kind: 'crud-kind', name: 'crud-name' }).save$()

    assert.ok(null != made.id)
    assert.equal(
      made.canon$({ string: true }),
      'provider/solardemo/planet',
    )

    const id = made.id

    try {
      const loaded = await ent.load$({ id: id })
      assert.equal(loaded.id, id)

      // An entity CARRYING an id is an update, not a second create.
      loaded.kind = 'crud-kind-2'
      const updated = await loaded.save$()

      assert.equal(updated.id, id)
      assert.equal(updated.kind, 'crud-kind-2')

      const reloaded = await ent.load$({ id: id })
      assert.equal(reloaded.kind, 'crud-kind-2')
    }
    finally {
      // Always clean up. The mock and the server both hold data for the
      // process lifetime, so a leaked record changes what later tests see.
      await ent.remove$({ id: id })
    }

    // remove is real: the record is gone, and reading it is an ordinary
    // not-found rather than an error.
    assert.equal(await ent.load$({ id: id }), null)
  })


  describe('live', () => {
    let live = false

    before(async () => {
      live = await serverUp(LIVE_BASE)
    })

    it('planet-list', async (t) => {
      if (!live) return t.skip(noServer())
      const seneca = await makeSeneca(liveOpts())

      const list = await seneca.entity('provider/solardemo/planet').list$()

      assert.ok(Array.isArray(list))
      if (0 < list.length) {
        assert.equal(
          list[0].canon$({ string: true }),
          'provider/solardemo/planet',
        )
      }
    })

    // A read of something that is not there is `null`, live as well as
    // offline: the provider's 404 handling is the same code path either way.
    it('planet-load-missing', async (t) => {
      if (!live) return t.skip(noServer())
      const seneca = await makeSeneca(liveOpts())

      assert.equal(
        await seneca
          .entity('provider/solardemo/planet')
          .load$('nosuchplanet'),
        null,
      )
    })

    it('moon-crud', async (t) => {
      if (!live) return t.skip(noServer())
      const seneca = await makeSeneca(liveOpts())
      const ent = seneca.entity('provider/solardemo/moon')

      // moon records hang off planet records, so the planet_id has to
      // come FROM THE SERVER. This database is not ours to seed.
      const planetRecords = await seneca
        .entity('provider/solardemo/planet')
        .list$()

      if (0 === planetRecords.length) return t.skip('no planet to attach a moon to')

      const planet_id = planetRecords[0].id

      // Seneca's convention: an entity WITHOUT an id is a create. The API
      // assigns the id itself, so the saved record comes back with one it chose.
      const made = await ent.make$({ planet_id, diameter: 12345, kind: 'crud-kind', name: 'crud-name' }).save$()

      assert.ok(null != made.id)
      assert.equal(
        made.canon$({ string: true }),
        'provider/solardemo/moon',
      )

      const id = made.id

      try {
        const loaded = await ent.load$({ planet_id, id: id })
        assert.equal(loaded.id, id)

        // An entity CARRYING an id is an update, not a second create.
        loaded.kind = 'crud-kind-2'
        const updated = await loaded.save$()

        assert.equal(updated.id, id)
        assert.equal(updated.kind, 'crud-kind-2')

        const reloaded = await ent.load$({ planet_id, id: id })
        assert.equal(reloaded.kind, 'crud-kind-2')
      }
      finally {
        // Always clean up. The mock and the server both hold data for the
        // process lifetime, so a leaked record changes what later tests see.
        await ent.remove$({ planet_id, id: id })
      }

      // remove is real: the record is gone, and reading it is an ordinary
      // not-found rather than an error.
      assert.equal(await ent.load$({ planet_id, id: id }), null)
    })

    it('planet-crud', async (t) => {
      if (!live) return t.skip(noServer())
      const seneca = await makeSeneca(liveOpts())
      const ent = seneca.entity('provider/solardemo/planet')

      // Seneca's convention: an entity WITHOUT an id is a create. The API
      // assigns the id itself, so the saved record comes back with one it chose.
      const made = await ent.make$({ diameter: 12345, kind: 'crud-kind', name: 'crud-name' }).save$()

      assert.ok(null != made.id)
      assert.equal(
        made.canon$({ string: true }),
        'provider/solardemo/planet',
      )

      const id = made.id

      try {
        const loaded = await ent.load$({ id: id })
        assert.equal(loaded.id, id)

        // An entity CARRYING an id is an update, not a second create.
        loaded.kind = 'crud-kind-2'
        const updated = await loaded.save$()

        assert.equal(updated.id, id)
        assert.equal(updated.kind, 'crud-kind-2')

        const reloaded = await ent.load$({ id: id })
        assert.equal(reloaded.kind, 'crud-kind-2')
      }
      finally {
        // Always clean up. The mock and the server both hold data for the
        // process lifetime, so a leaked record changes what later tests see.
        await ent.remove$({ id: id })
      }

      // remove is real: the record is gone, and reading it is an ordinary
      // not-found rather than an error.
      assert.equal(await ent.load$({ id: id }), null)
    })

  })


  it('maintain', async () => {
    const exclude = []

    // check_default proves the default branch is main by looking for
    // [branch "main"] in .git/config. Only a branch checkout records that
    // section: a pull_request build checks out the merge ref, and the
    // publish build checks out a tag as a detached HEAD. Neither says
    // anything about what the default branch is, so skip rather than fail.
    if ('pull_request' === process.env.GITHUB_EVENT_NAME ||
        'tag' === process.env.GITHUB_REF_TYPE) {
      exclude.push('check_default')
    }

    // url_pkgjson locates package.json by comparing process.cwd() + '/package.json'
    // against a path found with Filehound. On Windows those are the same file
    // spelt with different separators, so the url is never read.
    if ('win32' === process.platform) {
      exclude.push('url_pkgjson')
    }

    await Maintain({ exclude })
  })

})


function noServer() {
  return 'no solardemo server at ' + LIVE_BASE
}


function liveOpts() {
  return { sdk: { base: LIVE_BASE } }
}


// Probe the companion test server so live tests skip cleanly when it is not
// running, rather than failing the suite.
async function serverUp(base) {
  try {
    const res = await fetch(base + '/api/planet', {
      signal: AbortSignal.timeout(2000),
    })
    return res.ok
  }
  catch (e) {
    return false
  }
}


// Default to the SDK's offline mock transport, seeded from ./seed.
async function makeSeneca(pluginopts) {
  pluginopts = pluginopts || { test: true, testopts: SEED }

  const seneca = Seneca({ legacy: false })
    .test()
    .use('promisify')
    .use('entity')
    .use('env', {
      // Declared so the provider convention is exercised, and defaulted so
      // the suite runs with nothing configured.
      var: {
        $SOLARDEMO_APIKEY: '',
      },
    })
    .use('provider', {
      provider: {
        solardemo: {
          keys: {
            apikey: { value: '$SOLARDEMO_APIKEY' },
          },
        },
      },
    })
    .use(SolardemoProvider, pluginopts)

  return seneca.ready()
}
