// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(4,
      "name", v_str("VoxgigSolardemo"),
      "slug", v_str("voxgig-solardemo"),
      "version", v_str("0.1.0"),
      "target", v_str("c")),
    "feature", cmap(9,
      "debug", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "max", v_num(100),
          "redact", clist(7,
            v_str("authorization"),
            v_str("cookie"),
            v_str("set-cookie"),
            v_str("api-key"),
            v_str("apikey"),
            v_str("x-api-key"),
            v_str("idempotency-key"))),
        "optspec", cmap(2,
          "now", v_str("`$FUNCTION`"),
          "onEntry", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "idempotency", cmap(4,
        "options", cmap(4,
          "active", v_bool(false),
          "header", v_str("Idempotency-Key"),
          "methods", clist(4,
            v_str("POST"),
            v_str("PUT"),
            v_str("PATCH"),
            v_str("DELETE")),
          "ops", clist(3,
            v_str("create"),
            v_str("update"),
            v_str("remove"))),
        "optspec", cmap(1,
          "keygen", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "metrics", cmap(4,
        "options", cmap(1,
          "active", v_bool(false)),
        "optspec", cmap(1,
          "now", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "paging", cmap(4,
        "options", cmap(7,
          "active", v_bool(false),
          "afterVar", v_str("after"),
          "cursorParam", v_str("cursor"),
          "firstVar", v_str("first"),
          "limitParam", v_str("limit"),
          "pageParam", v_str("page"),
          "startPage", v_num(1)),
        "optspec", cmap(2,
          "limit", v_str("`$NUMBER`"),
          "ops", v_str("`$LIST`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "ratelimit", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "burst", v_num(5),
          "rate", v_num(5)),
        "optspec", cmap(2,
          "now", v_str("`$FUNCTION`"),
          "sleep", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "retry", cmap(4,
        "options", cmap(6,
          "active", v_bool(false),
          "factor", v_num(2),
          "maxDelay", v_num(2000),
          "minDelay", v_num(50),
          "retries", v_num(2),
          "statuses", clist(7,
            v_num(408),
            v_num(425),
            v_num(429),
            v_num(500),
            v_num(502),
            v_num(503),
            v_num(504))),
        "optspec", cmap(2,
          "jitter", v_str("`$BOOLEAN`"),
          "sleep", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "secrets", cmap(4,
        "options", cmap(5,
          "active", v_bool(false),
          "cache", v_bool(true),
          "exchange", cmap(8,
            "active", v_bool(false),
            "method", v_str("POST"),
            "path", v_str("auth/token"),
            "refresh", v_str(""),
            "request", v_str("refresh_token"),
            "response", v_str("access_token"),
            "retries", v_num(1),
            "statuses", clist(1,
              v_num(401))),
          "name", v_str("apikey"),
          "providers", v_list()),
        "optspec", v_map(),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "test", cmap(4,
        "options", cmap(1,
          "active", v_bool(false)),
        "optspec", cmap(2,
          "entity", v_str("`$MAP`"),
          "net", v_str("`$MAP`")),
        "strict", v_bool(false),
        "transport", v_str("base")),
      "timeout", cmap(4,
        "options", cmap(2,
          "active", v_bool(false),
          "ms", v_num(30000)),
        "optspec", cmap(2,
          "clearTimer", v_str("`$FUNCTION`"),
          "setTimer", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap"))),
    "options", cmap(3,
      "base", v_str("http://localhost:8901"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(2,
        "moon", v_map(),
        "planet", v_map())),
    "entity", cmap(2,
      "moon", cmap(5,
        "fields", clist(5,
          cmap(5,
            "name", v_str("diameter"),
            "title", v_str("Diameter"),
            "type", v_str("`$NUMBER`"),
            "req", v_bool(true),
            "format", v_str("float")),
          cmap(4,
            "name", v_str("id"),
            "title", v_str("Id"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true)),
          cmap(4,
            "name", v_str("kind"),
            "title", v_str("Kind"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true)),
          cmap(4,
            "name", v_str("name"),
            "title", v_str("Name"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true)),
          cmap(4,
            "name", v_str("planet_id"),
            "title", v_str("Planet Id"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("moon"),
        "op", cmap(5,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/api/planet/{planet_id}/moon"),
                "segments", clist(4,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("planet_id")),
                  cmap(1,
                    "lit", v_str("moon"))),
                "parts", clist(4,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{planet_id}"),
                  v_str("moon")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("planet_id"),
                      "orig", v_str("planet_id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("planet_id")))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/api/planet/{planet_id}/moon"),
                "segments", clist(4,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("planet_id")),
                  cmap(1,
                    "lit", v_str("moon"))),
                "parts", clist(4,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{planet_id}"),
                  v_str("moon")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("planet_id"),
                      "orig", v_str("planet_id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("planet_id")))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/api/planet/{planet_id}/moon/{moon_id}"),
                "segments", clist(5,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("planet_id")),
                  cmap(1,
                    "lit", v_str("moon")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(5,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{planet_id}"),
                  v_str("moon"),
                  v_str("{id}")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "moon_id", v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(2,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("moon_id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("planet_id"),
                      "orig", v_str("planet_id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("id"),
                    v_str("planet_id")))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/api/planet/{planet_id}/moon/{moon_id}"),
                "segments", clist(5,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("planet_id")),
                  cmap(1,
                    "lit", v_str("moon")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(5,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{planet_id}"),
                  v_str("moon"),
                  v_str("{id}")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "moon_id", v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(2,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("moon_id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("planet_id"),
                      "orig", v_str("planet_id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("id"),
                    v_str("planet_id")))))),
          "update", cmap(3,
            "input", v_str("data"),
            "name", v_str("update"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("PUT"),
                "orig", v_str("/api/planet/{planet_id}/moon/{moon_id}"),
                "segments", clist(5,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("planet_id")),
                  cmap(1,
                    "lit", v_str("moon")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(5,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{planet_id}"),
                  v_str("moon"),
                  v_str("{id}")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "moon_id", v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(2,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("moon_id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)),
                    cmap(5,
                      "name", v_str("planet_id"),
                      "orig", v_str("planet_id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("id"),
                    v_str("planet_id"))))))),
        "relations", cmap(1,
          "ancestors", clist(1,
            clist(1,
              v_str("$.main.kit.entity.planet"))))),
      "planet", cmap(5,
        "fields", clist(7,
          cmap(5,
            "name", v_str("diameter"),
            "title", v_str("Diameter"),
            "type", v_str("`$NUMBER`"),
            "req", v_bool(true),
            "format", v_str("float")),
          cmap(5,
            "name", v_str("forbidReason"),
            "title", v_str("Forbid Reason"),
            "type", v_str("`$STRING`"),
            "short", v_str("Why the planet is forbidden, carried from the forbid action's `why`."),
            "readOnly", v_bool(true)),
          cmap(5,
            "name", v_str("forbidState"),
            "title", v_str("Forbid State"),
            "type", v_str("`$STRING`"),
            "short", v_str("Set by the forbid action, and absent until it first runs."),
            "readOnly", v_bool(true)),
          cmap(4,
            "name", v_str("id"),
            "title", v_str("Id"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true)),
          cmap(4,
            "name", v_str("kind"),
            "title", v_str("Kind"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true)),
          cmap(4,
            "name", v_str("name"),
            "title", v_str("Name"),
            "type", v_str("`$STRING`"),
            "req", v_bool(true)),
          cmap(5,
            "name", v_str("terraformState"),
            "title", v_str("Terraform State"),
            "type", v_str("`$STRING`"),
            "short", v_str("Set by the terraform action, and absent until it first runs."),
            "readOnly", v_bool(true))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("planet"),
        "op", cmap(5,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(3,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/api/planet/{planet_id}/forbid"),
                "segments", clist(4,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("id")),
                  cmap(1,
                    "lit", v_str("forbid"))),
                "parts", clist(4,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{id}"),
                  v_str("forbid")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "planet_id", v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("planet_id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(2,
                  "$action", v_str("forbid"),
                  "exist", clist(1,
                    v_str("id")))),
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/api/planet/{planet_id}/terraform"),
                "segments", clist(4,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("id")),
                  cmap(1,
                    "lit", v_str("terraform"))),
                "parts", clist(4,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{id}"),
                  v_str("terraform")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "planet_id", v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("planet_id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(2,
                  "$action", v_str("terraform"),
                  "exist", clist(1,
                    v_str("id")))),
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/api/planet"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet"))),
                "parts", clist(2,
                  v_str("api"),
                  v_str("planet")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", v_map(),
                "select", v_map()))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/api/planet"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet"))),
                "parts", clist(2,
                  v_str("api"),
                  v_str("planet")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", v_map(),
                "select", v_map()))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/api/planet/{planet_id}"),
                "segments", clist(3,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(3,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{id}")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "planet_id", v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("planet_id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id")))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/api/planet/{planet_id}"),
                "segments", clist(3,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(3,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{id}")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "planet_id", v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("planet_id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id")))))),
          "update", cmap(3,
            "input", v_str("data"),
            "name", v_str("update"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("PUT"),
                "orig", v_str("/api/planet/{planet_id}"),
                "segments", clist(3,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(3,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{id}")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "planet_id", v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("planet_id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))))))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

// SHARED CONFIG (sdkgen rung L2).
//
// The SDK reads the config on every request and never writes to it, so one
// instance is shared by every client rather than rebuilt per client. Above the
// size threshold make_config re-parses the whole embedded JSON, so this is the
// difference between parsing the model once and once per client.
//
// Deliberately never freed: it lives for the life of the process, like any
// other program-lifetime singleton.
static voxgig_value* shared_config_val = NULL;

// The process-wide config, built once on first use.
//
// The returned value is SHARED: treat it as read-only. Callers that need to
// mutate should use make_config, which always returns a fresh copy.
voxgig_value* shared_config(void) {
  if (NULL == shared_config_val) {
    shared_config_val = make_config();
  }
  return shared_config_val;
}

Feature* feature_debug_new(void);
Feature* feature_idempotency_new(void);
Feature* feature_metrics_new(void);
Feature* feature_paging_new(void);
Feature* feature_ratelimit_new(void);
Feature* feature_retry_new(void);
Feature* feature_secrets_new(void);
Feature* feature_test_new(void);
Feature* feature_timeout_new(void);

Feature* make_feature(const char* name) {
  if (strcmp(name, "debug") == 0) return feature_debug_new();
  if (strcmp(name, "idempotency") == 0) return feature_idempotency_new();
  if (strcmp(name, "metrics") == 0) return feature_metrics_new();
  if (strcmp(name, "paging") == 0) return feature_paging_new();
  if (strcmp(name, "ratelimit") == 0) return feature_ratelimit_new();
  if (strcmp(name, "retry") == 0) return feature_retry_new();
  if (strcmp(name, "secrets") == 0) return feature_secrets_new();
  if (strcmp(name, "test") == 0) return feature_test_new();
  if (strcmp(name, "timeout") == 0) return feature_timeout_new();
  return feature_base_new();
}

void** secrets_plugins(size_t* n);

void** feature_plugins(const char* name, size_t* n) {
  if (strcmp(name, "secrets") == 0) return secrets_plugins(n);
  (void)name;
  *n = 0;
  return NULL;
}
