// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(4,
      "name", v_str("Solardemo"),
      "slug", v_str("solardemo"),
      "version", v_str("0.1.0"),
      "target", v_str("c")),
    "feature", cmap(1,
      "test", cmap(2,
        "options", cmap(1,
          "active", v_bool(false)),
        "transport", v_str("base"))),
    "options", cmap(3,
      "base", v_str("http://localhost:8901"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(2,
        "moon", v_map(),
        "planet", v_map())),
    "entity", cmap(2,
      "moon", cmap(4,
        "fields", clist(5,
          cmap(3,
            "name", v_str("diameter"),
            "req", v_bool(true),
            "type", v_str("`$NUMBER`")),
          cmap(3,
            "name", v_str("id"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("kind"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("name"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("planet_id"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("moon"),
        "op", cmap(5,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("planet_id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/api/planet/{planet_id}/moon"),
                "parts", clist(4,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{planet_id}"),
                  v_str("moon")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("planet_id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("planet_id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/api/planet/{planet_id}/moon"),
                "parts", clist(4,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{planet_id}"),
                  v_str("moon")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("planet_id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "params", clist(2,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("moon_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("planet_id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/api/planet/{planet_id}/moon/{moon_id}"),
                "parts", clist(5,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{planet_id}"),
                  v_str("moon"),
                  v_str("{id}")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "moon_id", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("id"),
                    v_str("planet_id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "params", clist(2,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("moon_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("planet_id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/api/planet/{planet_id}/moon/{moon_id}"),
                "parts", clist(5,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{planet_id}"),
                  v_str("moon"),
                  v_str("{id}")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "moon_id", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("id"),
                    v_str("planet_id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "update", cmap(3,
            "input", v_str("data"),
            "name", v_str("update"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "params", clist(2,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("moon_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("planet_id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("PUT"),
                "orig", v_str("/api/planet/{planet_id}/moon/{moon_id}"),
                "parts", clist(5,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{planet_id}"),
                  v_str("moon"),
                  v_str("{id}")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "moon_id", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("id"),
                    v_str("planet_id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", clist(1,
            clist(1,
              v_str("planet"))))),
      "planet", cmap(4,
        "fields", clist(10,
          cmap(3,
            "name", v_str("diameter"),
            "req", v_bool(true),
            "type", v_str("`$NUMBER`")),
          cmap(2,
            "name", v_str("forbid"),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("id"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("kind"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("name"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("ok"),
            "type", v_str("`$BOOLEAN`")),
          cmap(2,
            "name", v_str("start"),
            "type", v_str("`$BOOLEAN`")),
          cmap(2,
            "name", v_str("state"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("stop"),
            "type", v_str("`$BOOLEAN`")),
          cmap(2,
            "name", v_str("why"),
            "type", v_str("`$STRING`"))),
        "name", v_str("planet"),
        "op", cmap(5,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(3,
              cmap(8,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/api/planet/{planet_id}/forbid"),
                "parts", clist(4,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{id}"),
                  v_str("forbid")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "planet_id", v_str("id"))),
                "select", cmap(2,
                  "$action", v_str("forbid"),
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(8,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/api/planet/{planet_id}/terraform"),
                "parts", clist(4,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{id}"),
                  v_str("terraform")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "planet_id", v_str("id"))),
                "select", cmap(2,
                  "$action", v_str("terraform"),
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/api/planet"),
                "parts", clist(2,
                  v_str("api"),
                  v_str("planet")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/api/planet"),
                "parts", clist(2,
                  v_str("api"),
                  v_str("planet")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/api/planet/{planet_id}"),
                "parts", clist(3,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{id}")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "planet_id", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/api/planet/{planet_id}"),
                "parts", clist(3,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{id}")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "planet_id", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "update", cmap(3,
            "input", v_str("data"),
            "name", v_str("update"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("PUT"),
                "orig", v_str("/api/planet/{planet_id}"),
                "parts", clist(3,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{id}")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "planet_id", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

// SHARED CONFIG (sdkgen rung L2).
//
// The SDK reads the config on every request and never writes to it, so one
// instance is shared by every client rather than rebuilt per client. Above the
// size threshold make_config re-parses the whole embedded JSON, so this is the
// difference between parsing the model once and once per client.
//
// Deliberately never freed: it lives for the life of the process, like any
// other program-lifetime singleton.
static voxgig_value* shared_config_val = NULL;

// The process-wide config, built once on first use.
//
// The returned value is SHARED: treat it as read-only. Callers that need to
// mutate should use make_config, which always returns a fresh copy.
voxgig_value* shared_config(void) {
  if (NULL == shared_config_val) {
    shared_config_val = make_config();
  }
  return shared_config_val;
}

Feature* feature_test_new(void);

Feature* make_feature(const char* name) {
  if (strcmp(name, "test") == 0) return feature_test_new();
  return feature_base_new();
}
