// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(4,
      "name", v_str("Solardemo"),
      "slug", v_str("solardemo"),
      "version", v_str("0.1.0"),
      "target", v_str("c")),
    "feature", cmap(1,
      "test", cmap(2,
        "options", cmap(1,
          "active", v_bool(false)),
        "transport", v_str("base"))),
    "options", cmap(3,
      "base", v_str("http://localhost:8901"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(2,
        "moon", v_map(),
        "planet", v_map())),
    "entity", cmap(2,
      "moon", cmap(4,
        "fields", clist(5,
          cmap(4,
            "format", v_str("float"),
            "name", v_str("diameter"),
            "req", v_bool(true),
            "type", v_str("`$NUMBER`")),
          cmap(3,
            "name", v_str("id"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("kind"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("name"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("planet_id"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("moon"),
        "op", cmap(5,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("planet_id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "contract", cmap(4,
                  "id", v_str("POST /api/planet/{planet_id}/moon"),
                  "json", v_str("{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"planet_id\":{\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"planet_id\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"required\":true},\"responses\":{\"201\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"planet_id\":{\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"planet_id\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"description\":\"Created\"}},\"securitySource\":\"unspecified\"}"),
                  "source", v_str("openapi3"),
                  "version", v_num(1)),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/api/planet/{planet_id}/moon"),
                "segments", clist(4,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("planet_id")),
                  cmap(1,
                    "lit", v_str("moon"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("planet_id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(4,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{planet_id}"),
                  v_str("moon"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(9,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("planet_id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "contract", cmap(4,
                  "id", v_str("GET /api/planet/{planet_id}/moon"),
                  "json", v_str("{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"responses\":{\"200\":{\"content\":{\"application/json\":{\"schema\":{\"items\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"planet_id\":{\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"planet_id\",\"kind\",\"diameter\"],\"type\":\"object\"},\"type\":\"array\"}}},\"description\":\"OK\"}},\"securitySource\":\"unspecified\"}"),
                  "source", v_str("openapi3"),
                  "version", v_num(1)),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/api/planet/{planet_id}/moon"),
                "segments", clist(4,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("planet_id")),
                  cmap(1,
                    "lit", v_str("moon"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("planet_id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(4,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{planet_id}"),
                  v_str("moon"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(10,
                "args", cmap(1,
                  "params", clist(2,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("moon_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("planet_id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "contract", cmap(4,
                  "id", v_str("GET /api/planet/{planet_id}/moon/{moon_id}"),
                  "json", v_str("{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}},{\"in\":\"path\",\"name\":\"moon_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"responses\":{\"200\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"planet_id\":{\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"planet_id\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"description\":\"OK\"}},\"securitySource\":\"unspecified\"}"),
                  "source", v_str("openapi3"),
                  "version", v_num(1)),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/api/planet/{planet_id}/moon/{moon_id}"),
                "rename", cmap(1,
                  "param", cmap(1,
                    "moon_id", v_str("id"))),
                "segments", clist(5,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("planet_id")),
                  cmap(1,
                    "lit", v_str("moon")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("id"),
                    v_str("planet_id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(5,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{planet_id}"),
                  v_str("moon"),
                  v_str("{id}"))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(10,
                "args", cmap(1,
                  "params", clist(2,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("moon_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("planet_id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "contract", cmap(4,
                  "id", v_str("DELETE /api/planet/{planet_id}/moon/{moon_id}"),
                  "json", v_str("{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}},{\"in\":\"path\",\"name\":\"moon_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"responses\":{\"204\":{\"description\":\"No Content\"}},\"securitySource\":\"unspecified\"}"),
                  "source", v_str("openapi3"),
                  "version", v_num(1)),
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/api/planet/{planet_id}/moon/{moon_id}"),
                "rename", cmap(1,
                  "param", cmap(1,
                    "moon_id", v_str("id"))),
                "segments", clist(5,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("planet_id")),
                  cmap(1,
                    "lit", v_str("moon")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("id"),
                    v_str("planet_id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(5,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{planet_id}"),
                  v_str("moon"),
                  v_str("{id}"))))),
          "update", cmap(3,
            "input", v_str("data"),
            "name", v_str("update"),
            "points", clist(1,
              cmap(10,
                "args", cmap(1,
                  "params", clist(2,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("moon_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("planet_id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "contract", cmap(4,
                  "id", v_str("PUT /api/planet/{planet_id}/moon/{moon_id}"),
                  "json", v_str("{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}},{\"in\":\"path\",\"name\":\"moon_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"planet_id\":{\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"planet_id\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"required\":true},\"responses\":{\"200\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"planet_id\":{\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"planet_id\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"description\":\"OK\"}},\"securitySource\":\"unspecified\"}"),
                  "source", v_str("openapi3"),
                  "version", v_num(1)),
                "kind", v_str("http"),
                "method", v_str("PUT"),
                "orig", v_str("/api/planet/{planet_id}/moon/{moon_id}"),
                "rename", cmap(1,
                  "param", cmap(1,
                    "moon_id", v_str("id"))),
                "segments", clist(5,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("planet_id")),
                  cmap(1,
                    "lit", v_str("moon")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("id"),
                    v_str("planet_id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(5,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{planet_id}"),
                  v_str("moon"),
                  v_str("{id}")))))),
        "relations", cmap(1,
          "ancestors", clist(1,
            clist(1,
              v_str("planet"))))),
      "planet", cmap(4,
        "fields", clist(7,
          cmap(4,
            "format", v_str("float"),
            "name", v_str("diameter"),
            "req", v_bool(true),
            "type", v_str("`$NUMBER`")),
          cmap(4,
            "name", v_str("forbidReason"),
            "readOnly", v_bool(true),
            "short", v_str("Why the planet is forbidden, carried from the forbid action's `why`."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("forbidState"),
            "readOnly", v_bool(true),
            "short", v_str("Set by the forbid action, and absent until it first runs."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("id"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("kind"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("name"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("terraformState"),
            "readOnly", v_bool(true),
            "short", v_str("Set by the terraform action, and absent until it first runs."),
            "type", v_str("`$STRING`"))),
        "name", v_str("planet"),
        "op", cmap(5,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(3,
              cmap(10,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "contract", cmap(4,
                  "id", v_str("POST /api/planet/{planet_id}/forbid"),
                  "json", v_str("{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"forbid\":{\"type\":\"boolean\"},\"why\":{\"type\":\"string\"}},\"type\":\"object\"}}},\"required\":true},\"responses\":{\"200\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"ok\":{\"type\":\"boolean\"},\"state\":{\"type\":\"string\"}},\"type\":\"object\"}}},\"description\":\"OK\"}},\"securitySource\":\"unspecified\"}"),
                  "source", v_str("openapi3"),
                  "version", v_num(1)),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/api/planet/{planet_id}/forbid"),
                "rename", cmap(1,
                  "param", cmap(1,
                    "planet_id", v_str("id"))),
                "segments", clist(4,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("id")),
                  cmap(1,
                    "lit", v_str("forbid"))),
                "select", cmap(2,
                  "$action", v_str("forbid"),
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(4,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{id}"),
                  v_str("forbid"))),
              cmap(10,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "contract", cmap(4,
                  "id", v_str("POST /api/planet/{planet_id}/terraform"),
                  "json", v_str("{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"start\":{\"type\":\"boolean\"},\"stop\":{\"type\":\"boolean\"}},\"type\":\"object\"}}},\"required\":true},\"responses\":{\"200\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"ok\":{\"type\":\"boolean\"},\"state\":{\"type\":\"string\"}},\"type\":\"object\"}}},\"description\":\"OK\"}},\"securitySource\":\"unspecified\"}"),
                  "source", v_str("openapi3"),
                  "version", v_num(1)),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/api/planet/{planet_id}/terraform"),
                "rename", cmap(1,
                  "param", cmap(1,
                    "planet_id", v_str("id"))),
                "segments", clist(4,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("id")),
                  cmap(1,
                    "lit", v_str("terraform"))),
                "select", cmap(2,
                  "$action", v_str("terraform"),
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(4,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{id}"),
                  v_str("terraform"))),
              cmap(9,
                "args", v_map(),
                "contract", cmap(4,
                  "id", v_str("POST /api/planet"),
                  "json", v_str("{\"parameters\":[],\"protocol\":\"http\",\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"forbidReason\":{\"description\":\"Why the planet is forbidden, carried from the forbid action's `why`. Absent while the planet is allowed.\",\"readOnly\":true,\"type\":\"string\"},\"forbidState\":{\"description\":\"Set by the forbid action, and absent until it first runs. One of allowed or forbidden.\",\"readOnly\":true,\"type\":\"string\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"terraformState\":{\"description\":\"Set by the terraform action, and absent until it first runs. One of idle, terraforming or complete.\",\"readOnly\":true,\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"required\":true},\"responses\":{\"201\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"forbidReason\":{\"description\":\"Why the planet is forbidden, carried from the forbid action's `why`. Absent while the planet is allowed.\",\"readOnly\":true,\"type\":\"string\"},\"forbidState\":{\"description\":\"Set by the forbid action, and absent until it first runs. One of allowed or forbidden.\",\"readOnly\":true,\"type\":\"string\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"terraformState\":{\"description\":\"Set by the terraform action, and absent until it first runs. One of idle, terraforming or complete.\",\"readOnly\":true,\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"description\":\"Created\"}},\"securitySource\":\"unspecified\"}"),
                  "source", v_str("openapi3"),
                  "version", v_num(1)),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/api/planet"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("api"),
                  v_str("planet"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(9,
                "args", v_map(),
                "contract", cmap(4,
                  "id", v_str("GET /api/planet"),
                  "json", v_str("{\"parameters\":[],\"protocol\":\"http\",\"responses\":{\"200\":{\"content\":{\"application/json\":{\"schema\":{\"items\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"forbidReason\":{\"description\":\"Why the planet is forbidden, carried from the forbid action's `why`. Absent while the planet is allowed.\",\"readOnly\":true,\"type\":\"string\"},\"forbidState\":{\"description\":\"Set by the forbid action, and absent until it first runs. One of allowed or forbidden.\",\"readOnly\":true,\"type\":\"string\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"terraformState\":{\"description\":\"Set by the terraform action, and absent until it first runs. One of idle, terraforming or complete.\",\"readOnly\":true,\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"kind\",\"diameter\"],\"type\":\"object\"},\"type\":\"array\"}}},\"description\":\"OK\"}},\"securitySource\":\"unspecified\"}"),
                  "source", v_str("openapi3"),
                  "version", v_num(1)),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/api/planet"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("api"),
                  v_str("planet"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(10,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "contract", cmap(4,
                  "id", v_str("GET /api/planet/{planet_id}"),
                  "json", v_str("{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"responses\":{\"200\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"forbidReason\":{\"description\":\"Why the planet is forbidden, carried from the forbid action's `why`. Absent while the planet is allowed.\",\"readOnly\":true,\"type\":\"string\"},\"forbidState\":{\"description\":\"Set by the forbid action, and absent until it first runs. One of allowed or forbidden.\",\"readOnly\":true,\"type\":\"string\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"terraformState\":{\"description\":\"Set by the terraform action, and absent until it first runs. One of idle, terraforming or complete.\",\"readOnly\":true,\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"description\":\"OK\"}},\"securitySource\":\"unspecified\"}"),
                  "source", v_str("openapi3"),
                  "version", v_num(1)),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/api/planet/{planet_id}"),
                "rename", cmap(1,
                  "param", cmap(1,
                    "planet_id", v_str("id"))),
                "segments", clist(3,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(3,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{id}"))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(10,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "contract", cmap(4,
                  "id", v_str("DELETE /api/planet/{planet_id}"),
                  "json", v_str("{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"responses\":{\"204\":{\"description\":\"No Content\"}},\"securitySource\":\"unspecified\"}"),
                  "source", v_str("openapi3"),
                  "version", v_num(1)),
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/api/planet/{planet_id}"),
                "rename", cmap(1,
                  "param", cmap(1,
                    "planet_id", v_str("id"))),
                "segments", clist(3,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(3,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{id}"))))),
          "update", cmap(3,
            "input", v_str("data"),
            "name", v_str("update"),
            "points", clist(1,
              cmap(10,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("planet_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "contract", cmap(4,
                  "id", v_str("PUT /api/planet/{planet_id}"),
                  "json", v_str("{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"forbidReason\":{\"description\":\"Why the planet is forbidden, carried from the forbid action's `why`. Absent while the planet is allowed.\",\"readOnly\":true,\"type\":\"string\"},\"forbidState\":{\"description\":\"Set by the forbid action, and absent until it first runs. One of allowed or forbidden.\",\"readOnly\":true,\"type\":\"string\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"terraformState\":{\"description\":\"Set by the terraform action, and absent until it first runs. One of idle, terraforming or complete.\",\"readOnly\":true,\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"required\":true},\"responses\":{\"200\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"forbidReason\":{\"description\":\"Why the planet is forbidden, carried from the forbid action's `why`. Absent while the planet is allowed.\",\"readOnly\":true,\"type\":\"string\"},\"forbidState\":{\"description\":\"Set by the forbid action, and absent until it first runs. One of allowed or forbidden.\",\"readOnly\":true,\"type\":\"string\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"terraformState\":{\"description\":\"Set by the terraform action, and absent until it first runs. One of idle, terraforming or complete.\",\"readOnly\":true,\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"description\":\"OK\"}},\"securitySource\":\"unspecified\"}"),
                  "source", v_str("openapi3"),
                  "version", v_num(1)),
                "kind", v_str("http"),
                "method", v_str("PUT"),
                "orig", v_str("/api/planet/{planet_id}"),
                "rename", cmap(1,
                  "param", cmap(1,
                    "planet_id", v_str("id"))),
                "segments", clist(3,
                  cmap(1,
                    "lit", v_str("api")),
                  cmap(1,
                    "lit", v_str("planet")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(3,
                  v_str("api"),
                  v_str("planet"),
                  v_str("{id}")))))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

// SHARED CONFIG (sdkgen rung L2).
//
// The SDK reads the config on every request and never writes to it, so one
// instance is shared by every client rather than rebuilt per client. Above the
// size threshold make_config re-parses the whole embedded JSON, so this is the
// difference between parsing the model once and once per client.
//
// Deliberately never freed: it lives for the life of the process, like any
// other program-lifetime singleton.
static voxgig_value* shared_config_val = NULL;

// The process-wide config, built once on first use.
//
// The returned value is SHARED: treat it as read-only. Callers that need to
// mutate should use make_config, which always returns a fresh copy.
voxgig_value* shared_config(void) {
  if (NULL == shared_config_val) {
    shared_config_val = make_config();
  }
  return shared_config_val;
}

Feature* feature_test_new(void);

Feature* make_feature(const char* name) {
  if (strcmp(name, "test") == 0) return feature_test_new();
  return feature_base_new();
}
