package voxgig.voxgigsolardemosdk.core

import voxgig.voxgigsolardemosdk.utility.Json

/**
 * VoxgigSolardemo Kotlin SDK: generated schemas. Do not edit.
 *
 * Generated from the model: `main.kit.optspec` and each feature's
 * `config.options` for the option spec; entity `fields{}.type` for the
 * entity specs.
 */
@Suppress("UNCHECKED_CAST")
object Schema {

  // Parsed ONCE, on first use. The spec is read on every client construction
  // and never mutated, so a per-call parse would be pure waste — and a shared
  // map is safe for the same reason the spec is a constant: makeOptions
  // validates AGAINST it and writes into the options, never into the spec.
  //
  // 'by lazy' defaults to LazyThreadSafetyMode.SYNCHRONIZED, as
  // Config.sharedConfig uses, so concurrent first calls parse it exactly once.

  /** The option spec makeOptions validates client options against. */
  val optspec: MutableMap<String, Any?> by lazy {
    Json.parse(optspecJson()) as MutableMap<String, Any?>
  }

  /** Per-entity data and request specs, keyed by entity name. */
  val entityspec: MutableMap<String, Any?> by lazy {
    Json.parse(entityspecJson()) as MutableMap<String, Any?>
  }

  private fun optspecJson(): String {
    val b = StringBuilder()
    b.append("{")
    b.append(" \"allow\": {")
    b.append("  \"method\": \"GET,PUT,POST,PATCH,DELETE,OPTIONS\",")
    b.append("  \"op\": \"create,update,load,list,remove,command,direct,graphql\"")
    b.append(" },")
    b.append(" \"apikey\": \"\",")
    b.append(" \"auth\": {")
    b.append("  \"basic\": false,")
    b.append("  \"in\": \"\",")
    b.append("  \"name\": \"\",")
    b.append("  \"prefix\": \"\"")
    b.append(" },")
    b.append(" \"base\": \"http://localhost:8000\",")
    b.append(" \"clean\": {")
    b.append("  \"keys\": \"key,token,id\"")
    b.append(" },")
    b.append(" \"entity\": {")
    b.append("  \"`\$CHILD`\": {")
    b.append("   \"`\$OPEN`\": true,")
    b.append("   \"active\": false,")
    b.append("   \"alias\": {}")
    b.append("  }")
    b.append(" },")
    b.append(" \"extend\": \"`\$ANY`\",")
    b.append(" \"headers\": {")
    b.append("  \"`\$CHILD`\": \"`\$STRING`\"")
    b.append(" },")
    b.append(" \"prefix\": \"\",")
    b.append(" \"secret\": \"\",")
    b.append(" \"server\": {")
    b.append("  \"`\$CHILD`\": \"\"")
    b.append(" },")
    b.append(" \"suffix\": \"\",")
    b.append(" \"system\": {")
    b.append("  \"fetch\": \"`\$ANY`\"")
    b.append(" },")
    b.append(" \"test\": {")
    b.append("  \"active\": false,")
    b.append("  \"entity\": {")
    b.append("   \"`\$OPEN`\": true")
    b.append("  }")
    b.append(" },")
    b.append(" \"utility\": {},")
    b.append(" \"feature\": {")
    b.append("  \"`\$CHILD`\": {")
    b.append("   \"`\$OPEN`\": true,")
    b.append("   \"active\": false")
    b.append("  },")
    b.append("  \"debug\": [")
    b.append("   \"`\$ONE`\",")
    b.append("   {")
    b.append("    \"`\$OPEN`\": true,")
    b.append("    \"active\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$BOOLEAN`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"max\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$NUMBER`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"redact\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$LIST`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"now\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$FUNCTION`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"onEntry\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$FUNCTION`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ]")
    b.append("   },")
    b.append("   \"`\$NIL`\"")
    b.append("  ],")
    b.append("  \"idempotency\": [")
    b.append("   \"`\$ONE`\",")
    b.append("   {")
    b.append("    \"`\$OPEN`\": true,")
    b.append("    \"active\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$BOOLEAN`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"header\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$STRING`\",")
    b.append("     [")
    b.append("      \"`\$EXACT`\",")
    b.append("      \"\"")
    b.append("     ],")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"methods\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$LIST`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"ops\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$LIST`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"keygen\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$FUNCTION`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ]")
    b.append("   },")
    b.append("   \"`\$NIL`\"")
    b.append("  ],")
    b.append("  \"metrics\": [")
    b.append("   \"`\$ONE`\",")
    b.append("   {")
    b.append("    \"`\$OPEN`\": true,")
    b.append("    \"active\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$BOOLEAN`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"now\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$FUNCTION`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ]")
    b.append("   },")
    b.append("   \"`\$NIL`\"")
    b.append("  ],")
    b.append("  \"paging\": [")
    b.append("   \"`\$ONE`\",")
    b.append("   {")
    b.append("    \"`\$OPEN`\": true,")
    b.append("    \"active\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$BOOLEAN`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"afterVar\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$STRING`\",")
    b.append("     [")
    b.append("      \"`\$EXACT`\",")
    b.append("      \"\"")
    b.append("     ],")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"cursorParam\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$STRING`\",")
    b.append("     [")
    b.append("      \"`\$EXACT`\",")
    b.append("      \"\"")
    b.append("     ],")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"firstVar\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$STRING`\",")
    b.append("     [")
    b.append("      \"`\$EXACT`\",")
    b.append("      \"\"")
    b.append("     ],")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"limitParam\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$STRING`\",")
    b.append("     [")
    b.append("      \"`\$EXACT`\",")
    b.append("      \"\"")
    b.append("     ],")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"pageParam\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$STRING`\",")
    b.append("     [")
    b.append("      \"`\$EXACT`\",")
    b.append("      \"\"")
    b.append("     ],")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"startPage\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$NUMBER`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"limit\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$NUMBER`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"ops\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$LIST`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ]")
    b.append("   },")
    b.append("   \"`\$NIL`\"")
    b.append("  ],")
    b.append("  \"ratelimit\": [")
    b.append("   \"`\$ONE`\",")
    b.append("   {")
    b.append("    \"`\$OPEN`\": true,")
    b.append("    \"active\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$BOOLEAN`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"burst\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$NUMBER`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"rate\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$NUMBER`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"now\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$FUNCTION`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"sleep\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$FUNCTION`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ]")
    b.append("   },")
    b.append("   \"`\$NIL`\"")
    b.append("  ],")
    b.append("  \"retry\": [")
    b.append("   \"`\$ONE`\",")
    b.append("   {")
    b.append("    \"`\$OPEN`\": true,")
    b.append("    \"active\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$BOOLEAN`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"factor\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$NUMBER`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"maxDelay\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$NUMBER`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"minDelay\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$NUMBER`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"retries\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$NUMBER`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"statuses\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$LIST`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"jitter\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$BOOLEAN`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"sleep\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$FUNCTION`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ]")
    b.append("   },")
    b.append("   \"`\$NIL`\"")
    b.append("  ],")
    b.append("  \"secrets\": [")
    b.append("   \"`\$ONE`\",")
    b.append("   {")
    b.append("    \"`\$OPEN`\": true,")
    b.append("    \"active\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$BOOLEAN`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"cache\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$BOOLEAN`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"exchange\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$MAP`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"name\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$STRING`\",")
    b.append("     [")
    b.append("      \"`\$EXACT`\",")
    b.append("      \"\"")
    b.append("     ],")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"providers\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$LIST`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ]")
    b.append("   },")
    b.append("   \"`\$NIL`\"")
    b.append("  ],")
    b.append("  \"test\": [")
    b.append("   \"`\$ONE`\",")
    b.append("   {")
    b.append("    \"`\$OPEN`\": true,")
    b.append("    \"active\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$BOOLEAN`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"entity\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$MAP`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"net\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$MAP`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ]")
    b.append("   },")
    b.append("   \"`\$NIL`\"")
    b.append("  ],")
    b.append("  \"timeout\": [")
    b.append("   \"`\$ONE`\",")
    b.append("   {")
    b.append("    \"`\$OPEN`\": true,")
    b.append("    \"active\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$BOOLEAN`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"ms\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$NUMBER`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"clearTimer\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$FUNCTION`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ],")
    b.append("    \"setTimer\": [")
    b.append("     \"`\$ONE`\",")
    b.append("     \"`\$FUNCTION`\",")
    b.append("     \"`\$NIL`\"")
    b.append("    ]")
    b.append("   },")
    b.append("   \"`\$NIL`\"")
    b.append("  ]")
    b.append(" }")
    b.append("}")
    return b.toString()
  }

  private fun entityspecJson(): String {
    val b = StringBuilder()
    b.append("{}")
    return b.toString()
  }
}
