(* Solardemo SDK client (generated by @voxgig/sdkgen).
 *
 * The SDK "object" is the runtime sdk_client record (see Sdk_types). These
 * constructors wire the embedded config + feature factory (Sdk_config) into
 * the API-agnostic client builders (Sdk_features.make_client_base / sdk_test).
 * Entity accessors return an entity_obj whose CRUD closures run the pipeline. *)

open Voxgig_struct
open Sdk_types
open Sdk_features

(* Construct a live client from options (Noval for defaults). *)
let make (options : value) : sdk_client =
  make_client_base
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    options

(* No-argument convenience constructor. *)
let make0 () : sdk_client = make Noval

(* Construct a client in test mode (in-memory mock transport). *)
let test () : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    Noval Noval

(* Test-mode client with explicit test / sdk options. *)
let test_with (testopts : value) (sdkopts : value) : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    testopts sdkopts

(* Low-level escape hatches (raw transport call / request preparation). *)
let direct (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.direct client fetchargs

let graphql (client : sdk_client) (query : string) (variables : value)
    (ctrl : value) : value =
  Sdk_features.graphql client query variables ctrl

let prepare (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.prepare client fetchargs

(* Moon entity bound to a client:  moon client entopts *)
let moon (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_moon.make client entopts

(* Planet entity bound to a client:  planet client entopts *)
let planet (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_planet.make client entopts
