(* Solardemo SDK Planet entity (generated by @voxgig/sdkgen).
 *
 * An entity is a mutable entity_obj record (see Sdk_types): its CRUD closures
 * drive the operation pipeline through run_op. Missing ops install a stub that
 * errors at call time so the record is always fully populated. *)

open Voxgig_struct
open Sdk_types
open Sdk_helpers
open Sdk_runtime

exception Op_return of value

(* Run the operation pipeline, firing feature hooks between stages via the
 * generated hook-marker lines. post_done runs after the PreDone stage, just
 * before done. Errors from any stage go through make_error (which either
 * returns resdata when throw is disabled, or raises). *)
let run_op (ctx : ctx) (post_done : unit -> unit) : value =
  let utility = cu ctx in
  let bail (err : sdk_error option) = raise (Op_return (utility.u_make_error ctx err)) in
  try
    (try
       feature_hook ctx "PrePoint";
       let point = (match utility.u_make_point ctx with (p, None) -> p | (_, e) -> bail e) in
       Hashtbl.replace ctx.c_out "point" (OPoint point);
       feature_hook ctx "PreSpec";
       let spec = (match utility.u_make_spec ctx with (Some s, None) -> s | (_, e) -> bail e) in
       Hashtbl.replace ctx.c_out "spec" (OSpec spec);
       feature_hook ctx "PreRequest";
       let resp = (match utility.u_make_request ctx with (Some r, None) -> r | (_, e) -> bail e) in
       Hashtbl.replace ctx.c_out "request" (OResponse resp);
       feature_hook ctx "PreResponse";
       let resp2 = (match utility.u_make_response ctx with (Some r, None) -> r | (_, e) -> bail e) in
       Hashtbl.replace ctx.c_out "response" (OResponse resp2);
       feature_hook ctx "PreResult";
       let result = (match utility.u_make_result ctx with (Some r, None) -> r | (_, e) -> bail e) in
       Hashtbl.replace ctx.c_out "result" (OResult result);
       feature_hook ctx "PreDone";
       post_done ();
       utility.u_done ctx
     with Op_return v -> v)
  with
  | Sdk_error_exc _ as e ->
    feature_hook ctx "PreUnexpected";
    raise e

let rec make (client : sdk_client) (entopts_in : value) : entity_obj =
  let entopts = match to_map entopts_in with Map _ as m -> m | _ -> empty_map () in
  (match getp entopts "active" with Bool false -> () | _ -> setp entopts "active" (Bool true));
  let utility = client.cl_utility in
  let root =
    match client.cl_rootctx with Some c -> c | None -> failwith "root context not initialised" in
  let ent = {
    e_name = "planet";
    e_client = client;
    e_utility = utility;
    e_entopts = entopts;
    e_data = empty_map ();
    e_match = empty_map ();
    e_entctx = root;
    e_make = (fun () -> make client entopts);
    e_data_set = (fun _ -> ());
    e_data_get = (fun () -> empty_map ());
    e_match_set = (fun _ -> ());
    e_match_get = (fun () -> empty_map ());
    (* Placeholders: the real closures are installed below. They cannot name
     * `ent` here, and the op signatures resolve to entity_obj, so failwith
     * (which types as 'a) stands in. *)
    e_load = (fun _ _ -> failwith "op not installed");
    e_list = (fun _ _ -> failwith "op not installed");
    e_create = (fun _ _ -> failwith "op not installed");
    e_update = (fun _ _ -> failwith "op not installed");
    e_remove = (fun _ _ -> failwith "op not installed");
    e_deleted = false;
    e_mark_deleted = (fun () -> ());
    e_stream = (fun _ _ _ -> Seq.empty);
  } in
  let entctx = utility.u_make_context
      { (default_ctxspec ()) with cs_entity = Some ent; cs_entopts = Some entopts } (Some root) in
  ent.e_entctx <- entctx;
  utility.u_feature_hook entctx "PostConstructEntity";
  ent.e_data_set <- (fun args ->
      if not (is_nullish args) then begin
        ent.e_data <- (match to_map (clone args) with Map _ as m -> m | _ -> empty_map ());
        utility.u_feature_hook entctx "SetData"
      end);
  ent.e_data_get <- (fun () -> utility.u_feature_hook entctx "GetData"; clone ent.e_data);
  ent.e_match_set <- (fun args ->
      if not (is_nullish args) then begin
        ent.e_match <- (match to_map (clone args) with Map _ as m -> m | _ -> empty_map ());
        utility.u_feature_hook entctx "SetMatch"
      end);
  ent.e_match_get <- (fun () -> utility.u_feature_hook entctx "GetMatch"; clone ent.e_match);
  ent.e_mark_deleted <- (fun () -> ent.e_deleted <- true);
  (* Streaming operation. Runs `action` (an op name, e.g. "list") through the
   * full pipeline and returns a lazy Seq over result items, so the streaming
   * feature's incremental output is reachable (a normal op call materialises
   * the whole result). When the streaming feature is active the result carries
   * a stream closure and this yields from it (honouring chunkSize); otherwise
   * it falls back to the materialised items, so stream always yields.
   * callopts parameterises the call: ctrl (per-call pipeline control), body (an
   * enumerable/list payload attached to the request for outbound streaming),
   * and signal (a 0-arity fn -> Bool; iteration stops when it returns true). *)
  ent.e_stream <- (fun action args callopts ->
      let callopts = match to_map callopts with Map _ as m -> m | _ -> empty_map () in
      let ctrl = match to_map (getp callopts "ctrl") with Map _ as m -> m | _ -> empty_map () in
      setp ctrl "stream" callopts;
      let reqmatch = match to_map args with Map _ as m -> m | _ -> empty_map () in
      let ctx = utility.u_make_context
          { (default_ctxspec ()) with
            cs_opname = Some action;
            cs_ctrl = Some ctrl;
            cs_match = Some ent.e_match; cs_data = Some ent.e_data;
            cs_reqmatch = Some reqmatch }
          (Some entctx) in
      let body = getp callopts "body" in
      (if not (is_nullish body) then begin
         let reqdata = match to_map ctx.c_reqdata with Map _ as m -> m | _ -> empty_map () in
         setp reqdata "body$" body;
         ctx.c_reqdata <- reqdata;
         scratch_set ctx "stream_out" body
       end);
      ignore (run_op ctx (fun () -> ()));
      let signal = getp callopts "signal" in
      let aborted () = match signal with Func _ -> call_json signal = Bool true | _ -> false in
      let raw = (match ctx.c_result with
          | Some result ->
            (match result.rt_stream with
             | Some fn -> fn ()
             | None -> (match result.rt_resdata with List r -> !r | v when is_nullish v -> [] | v -> [v]))
          | None -> []) in
      let rec seq_of l () = match l with
        | [] -> Seq.Nil
        | x :: rest -> if aborted () then Seq.Nil else Seq.Cons (x, seq_of rest) in
      seq_of raw);
  ignore run_op;
  ent.e_load <- (fun reqmatch ctrl ->
      let reqmatch = if is_nullish reqmatch then empty_map () else reqmatch in
      let ctx = utility.u_make_context
          { (default_ctxspec ()) with
            cs_opname = Some "load";
            cs_ctrl = (match ctrl with Noval | Null -> None | c -> Some c);
            cs_match = Some ent.e_match; cs_data = Some ent.e_data;
            cs_reqmatch = Some reqmatch }
          (Some entctx) in
      let post_done () =
          match ctx.c_result with
          | Some result ->
            (match result.rt_resmatch with Map _ as m -> ent.e_match <- m | _ -> ());
            if not (is_nullish result.rt_resdata) then
              ent.e_data <- (match to_map (clone result.rt_resdata) with Map _ as m -> m | _ -> empty_map ());
          | None -> () in
      ignore (run_op ctx post_done);
      ent);
  ent.e_list <- (fun reqmatch ctrl ->
      let reqmatch = if is_nullish reqmatch then empty_map () else reqmatch in
      let ctx = utility.u_make_context
          { (default_ctxspec ()) with
            cs_opname = Some "list";
            cs_ctrl = (match ctrl with Noval | Null -> None | c -> Some c);
            cs_match = Some ent.e_match; cs_data = Some ent.e_data;
            cs_reqmatch = Some reqmatch }
          (Some entctx) in
      let post_done () =
          match ctx.c_result with
          | Some result ->
            (match result.rt_resmatch with Map _ as m -> ent.e_match <- m | _ -> ());
          | None -> () in
      let out = run_op ctx post_done in
      (match out with
       | List items ->
         List.map (fun entry ->
             let e = ent.e_make () in
             (match entry with Map _ -> e.e_data_set entry | _ -> ());
             e)
           !items
       | _ -> []));
  ent.e_create <- (fun reqdata ctrl ->
      let reqdata = if is_nullish reqdata then empty_map () else reqdata in
      let ctx = utility.u_make_context
          { (default_ctxspec ()) with
            cs_opname = Some "create";
            cs_ctrl = (match ctrl with Noval | Null -> None | c -> Some c);
            cs_match = Some ent.e_match; cs_data = Some ent.e_data;
            cs_reqdata = Some reqdata }
          (Some entctx) in
      let post_done () =
          match ctx.c_result with
          | Some result ->
            if not (is_nullish result.rt_resdata) then
              ent.e_data <- (match to_map (clone result.rt_resdata) with Map _ as m -> m | _ -> empty_map ());
          | None -> () in
      ignore (run_op ctx post_done);
      ent);
  ent.e_update <- (fun reqdata ctrl ->
      let reqdata = if is_nullish reqdata then empty_map () else reqdata in
      let ctx = utility.u_make_context
          { (default_ctxspec ()) with
            cs_opname = Some "update";
            cs_ctrl = (match ctrl with Noval | Null -> None | c -> Some c);
            cs_match = Some ent.e_match; cs_data = Some ent.e_data;
            cs_reqdata = Some reqdata }
          (Some entctx) in
      let post_done () =
          match ctx.c_result with
          | Some result ->
            (match result.rt_resmatch with Map _ as m -> ent.e_match <- m | _ -> ());
            if not (is_nullish result.rt_resdata) then
              ent.e_data <- (match to_map (clone result.rt_resdata) with Map _ as m -> m | _ -> empty_map ());
          | None -> () in
      ignore (run_op ctx post_done);
      ent);
  ent.e_remove <- (fun reqmatch ctrl ->
      let reqmatch = if is_nullish reqmatch then empty_map () else reqmatch in
      let ctx = utility.u_make_context
          { (default_ctxspec ()) with
            cs_opname = Some "remove";
            cs_ctrl = (match ctrl with Noval | Null -> None | c -> Some c);
            cs_match = Some ent.e_match; cs_data = Some ent.e_data;
            cs_reqmatch = Some reqmatch }
          (Some entctx) in
      let post_done () =
          match ctx.c_result with
          | Some result ->
            (match result.rt_resmatch with Map _ as m -> ent.e_match <- m | _ -> ());
            if not (is_nullish result.rt_resdata) then
              ent.e_data <- (match to_map (clone result.rt_resdata) with Map _ as m -> m | _ -> empty_map ());
          | None -> () in
      ignore (run_op ctx post_done);
      ent.e_mark_deleted ();
      ent);
  ent
