// Solardemo SDK for Rust (generated by @voxgig/sdkgen).
//
// The crate mirrors the go SDK layout: core/ (pipeline types), feature/
// (pipeline features), utility/ (pipeline utilities + the vendored voxgig
// struct port), entity/ (per-entity clients). The crate root is this file
// (see Cargo.toml [lib] path).

pub mod core;
pub mod entity;
pub mod feature;
pub mod utility;

// Public API re-exports.
pub use crate::core::config::{make_config, make_feature};
pub use crate::core::context::{Context, CtxSpec, OpMap};
pub use crate::core::control::Control;
pub use crate::core::error::SolardemoError;
pub use crate::core::helpers::{
    call_json, call_vfn, ja, jo, json_thunk, unsupported_op, vfn,
};
pub use crate::core::operation::Operation;
pub use crate::core::point::Point;
pub use crate::core::response::Response;
pub use crate::core::result::{SdkResult, StreamFn};
pub use crate::core::sdk::{test_sdk, SolardemoSDK};
pub use crate::core::spec::Spec;
pub use crate::core::types::{
    Entity, Feature, FeatureRef, FetcherFn, OutVal, SolardemoEntity,
};
pub use crate::core::utility_type::Utility;
pub use crate::feature::base::BaseFeature;
pub use crate::utility::jsonparse::json_parse;
pub use crate::utility::voxgigstruct::Value;

// No-argument convenience constructors: `solardemo_sdk::new()` /
// `solardemo_sdk::test()` for the common no-options case.
use std::rc::Rc;

pub fn new() -> Rc<SolardemoSDK> {
    SolardemoSDK::new(Value::Noval)
}

pub fn test() -> Rc<SolardemoSDK> {
    test_sdk(Value::Noval, Value::Noval)
}
