const std = @import("std");

// VoxgigSolardemo SDK for Zig (generated by @voxgig/sdkgen).
//
// Layout mirrors the other targets: src/core (pipeline types), src/feature
// (pipeline features), src/utility (pipeline utilities + the vendored voxgig
// struct port), src/entity (per-entity clients). The vendored struct port is
// exposed as the "voxgig-struct" module so the corpus runner can import it,
// and the whole SDK is exposed as the "sdk" module (root: root.zig).
//
// TOOLCHAIN: zig 0.16. A test artifact takes a `root_module` rather than a
// `root_source_file`, so each test file gets its own module built here with
// the struct and sdk modules already imported.
//
// The Zig test framework can crash with signal 11 during cleanup *after* all
// tests pass, due to *MapRef/*ListRef cross-references in arena teardown. The
// Makefile filters the output: "N/N tests passed" with N==total is success.
//
// GENERATED from src/cmp/zig/fragment/Build.fragment.zig (Main_zig): the
// `// #...` marker lines there are slots the generator fills from the model -
// a GATED feature's build modules and its test step appear only when the
// feature is active, so an SDK without that feature declares none of them.
pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // Vendored struct port module (its JsonValue is the SDK data model).
    const struct_mod = b.addModule("voxgig-struct", .{
        .root_source_file = b.path("utility/voxgigstruct/struct.zig"),
        .target = target,
        .optimize = optimize,
    });

    // The vendored @voxgig/omni port: the corpus test ENGINE, driven by
    // test/omniresolver.zig. A MODULE, not a path import, for two reasons:
    // omni.zig reaches its own regex.zig by path, so the pair must belong to
    // exactly one module; and `@import("omni")` cannot then be confused with
    // the resolver that adapts it.
    const omni_mod = b.addModule("omni", .{
        .root_source_file = b.path("test/vendor/omni/omni.zig"),
        .target = target,
        .optimize = optimize,
    });

    // The SDK module (root re-exports the public surface).
    const sdk_mod = b.addModule("sdk", .{
        .root_source_file = b.path("root.zig"),
        .target = target,
        .optimize = optimize,
    });
    sdk_mod.addImport("voxgig-struct", struct_mod);
    // The secrets feature's vendored libraries (@voxgig/sekreto and
    // voxgig/plugin at the shared vendor tag), as the three named modules
    // upstream builds them as. Declared ONLY when the model activates the
    // feature: feature/secrets.zig is the sole importer, and an inactive SDK
    // never analyses it (zig compiles only what a module root reaches).
    const plugin_mod = b.addModule("plugin", .{
        .root_source_file = b.path("feature/secrets/plugin/plugin.zig"),
        .target = target,
        .optimize = optimize,
    });
    const sekreto_mod = b.addModule("sekreto", .{
        .root_source_file = b.path("feature/secrets/sekreto/sekreto.zig"),
        .target = target,
        .optimize = optimize,
    });
    sekreto_mod.addImport("plugin", plugin_mod);
    // Rooted at the GENERATED selection (feature/secrets/plugins.zig), never
    // at upstream's full-set all.zig: the root decides which kinds compile.
    const sekretoplugins_mod = b.addModule("sekretoplugins", .{
        .root_source_file = b.path("feature/secrets/plugins.zig"),
        .target = target,
        .optimize = optimize,
    });
    sekretoplugins_mod.addImport("sekreto", sekreto_mod);
    sekretoplugins_mod.addImport("plugin", plugin_mod);
    sdk_mod.addImport("sekreto", sekreto_mod);
    sdk_mod.addImport("sekretoplugins", sekretoplugins_mod);

    const test_step = b.step("test", "Run all tests");

    // Every test file: gets the struct, sdk and omni modules.
    const test_files = [_][]const u8{
        "test/struct_corpus.zig",
        "test/generated_test.zig",
        "test/pipeline_test.zig",
        "test/feature_test.zig",
        "test/primary_utility_test.zig",
        "test/gotcha_test.zig",
        "test/omnismoke_test.zig",
    };

    for (test_files) |tf| {
        const test_mod = b.createModule(.{
            .root_source_file = b.path(tf),
            .target = target,
            .optimize = optimize,
        });
        test_mod.addImport("voxgig-struct", struct_mod);
        test_mod.addImport("sdk", sdk_mod);
        test_mod.addImport("omni", omni_mod);

        const t = b.addTest(.{ .root_module = test_mod });
        const run_t = b.addRunArtifact(t);
        run_t.has_side_effects = true;
        test_step.dependOn(&run_t.step);
    }
    // The secrets feature suite: part of `zig build test`, and alone as
    // `zig build test-secrets` (see FEATURE_TESTS in Main_zig).
    {
        const secrets_mod = b.createModule(.{
            .root_source_file = b.path("test/feature/secrets/secrets_test.zig"),
            .target = target,
            .optimize = optimize,
        });
        secrets_mod.addImport("voxgig-struct", struct_mod);
        secrets_mod.addImport("sdk", sdk_mod);
        secrets_mod.addImport("omni", omni_mod);
        const secrets_test = b.addTest(.{ .root_module = secrets_mod });
        const run_secrets = b.addRunArtifact(secrets_test);
        run_secrets.has_side_effects = true;
        test_step.dependOn(&run_secrets.step);
        const secrets_step = b.step("test-secrets", "Run the secrets feature suite alone");
        secrets_step.dependOn(&run_secrets.step);
    }
}
