-- Solardemo SDK test runner (generated by @voxgig/sdkgen).
--
-- OFFLINE lane (always): a test-mode client seeded from the generated entity
-- test data answers operations from an in-memory store — no server needed.
-- LIVE lane (only when SDK_TEST_BASE is set): the same flow over real HTTP.

import VoxgigStruct
import SdkJson
import SdkRuntime
import SdkClient

open VoxgigStruct

initialize npass : IO.Ref Nat ← IO.mkRef 0
initialize nfail : IO.Ref Nat ← IO.mkRef 0

def pass (msg : String) : SIO Unit := do
  npass.modify (· + 1)
  IO.println s!"ok   - {msg}"

def fail (msg : String) : SIO Unit := do
  nfail.modify (· + 1)
  IO.println s!"FAIL - {msg}"

def defaultBase : String := "http://localhost:8901"

def main : IO UInt32 := do
  let liveBase ← IO.getEnv "SDK_TEST_BASE"
  let ctx ← mkCtx
  let offline : SIO Unit := do
    -- moon: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/moon/MoonTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - moon: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "moon"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Moon.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"moon.list offline -> {n} seeded"
        else fail s!"moon.list offline: got {n}, want {ids.size}"
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Moon.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"moon.load offline (id={wid})"
          else fail s!"moon.load offline: got {gid}, want {wid}"
        -- create -> load back -> remove, all in the store
        let newmap ← SdkRuntime.gp (← SdkRuntime.gp seed "new") "moon"
        let nks ← keysof newmap
        if nks.size > 0 then do
          let payload ← SdkRuntime.gp newmap nks[0]!
          let created ← Moon.create tclient payload (← emptyMap)
          let cid ← SdkRuntime.gpS created "id"
          if cid == "" then fail "moon.create offline returned no id" else do
            let m2 ← newMap #[("id", Value.str cid)]
            let back ← Moon.load tclient m2 (← emptyMap)
            if (← SdkRuntime.gpS back "id") == cid then
              pass s!"moon.create/load offline (id={cid})"
            else fail s!"moon.create/load offline mismatch"
            let _ ← Moon.remove tclient m2 (← emptyMap)
            let gone ← Moon.load tclient m2 (← emptyMap)
            match gone with
            | Value.map _ => fail s!"moon.remove offline: still present"
            | _ => pass s!"moon.remove offline (id={cid})"
)
    -- planet: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/planet/PlanetTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - planet: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "planet"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Planet.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"planet.list offline -> {n} seeded"
        else fail s!"planet.list offline: got {n}, want {ids.size}"
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Planet.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"planet.load offline (id={wid})"
          else fail s!"planet.load offline: got {gid}, want {wid}"
        -- create -> load back -> remove, all in the store
        let newmap ← SdkRuntime.gp (← SdkRuntime.gp seed "new") "planet"
        let nks ← keysof newmap
        if nks.size > 0 then do
          let payload ← SdkRuntime.gp newmap nks[0]!
          let created ← Planet.create tclient payload (← emptyMap)
          let cid ← SdkRuntime.gpS created "id"
          if cid == "" then fail "planet.create offline returned no id" else do
            let m2 ← newMap #[("id", Value.str cid)]
            let back ← Planet.load tclient m2 (← emptyMap)
            if (← SdkRuntime.gpS back "id") == cid then
              pass s!"planet.create/load offline (id={cid})"
            else fail s!"planet.create/load offline mismatch"
            let _ ← Planet.remove tclient m2 (← emptyMap)
            let gone ← Planet.load tclient m2 (← emptyMap)
            match gone with
            | Value.map _ => fail s!"planet.remove offline: still present"
            | _ => pass s!"planet.remove offline (id={cid})"
)
  offline.run ctx
  match liveBase with
  | none => IO.println "skip - live lane (set SDK_TEST_BASE to enable)"
  | some base => do
    let live : SIO Unit := do
      let opts ← newMap #[("base", .str base)]
      let client ← Sdk.newSdk opts
      -- planet: list smoke
      (do
        let items ← Planet.list client (← emptyMap) (← emptyMap)
        match items with
        | Value.list lid => pass s!"planet.list -> {(← listItems lid).size} items"
        | _ => fail "planet.list did not return a list")
      -- planet: create / load / remove round-trip
      (do
        let d ← SdkJson.jsonRead "{\"diameter\":42,\"kind\":\"leantest\",\"name\":\"leantest\"}"
        let created ← Planet.create client d (← emptyMap)
        let nid ← SdkRuntime.gpS created "id"
        if nid == "" then fail "planet.create returned no id" else do
          let m ← newMap #[("id", .str nid)]
          let back ← Planet.load client m (← emptyMap)
          let bid ← SdkRuntime.gpS back "id"
          if bid == nid then pass s!"planet.create/load round-trip (id={nid})"
          else fail s!"planet.load mismatch: {bid} != {nid}"
          let _ ← Planet.remove client m (← emptyMap)
          pass s!"planet.remove (id={nid})")
    live.run ctx
  let p ← npass.get
  let f ← nfail.get
  IO.println ""
  IO.println s!"PASS {p}  FAIL {f}"
  if f > 0 then return 1 else return 0
