/* Generated by @voxgig/sdkgen. Do not edit. */

const Pkg = require('../package.json')

const { SolardemoSDK } = require('@voxgig-sdk/solardemo')

const SdkPkg = require('@voxgig-sdk/solardemo/package.json')


type SolardemoProviderOptions = {
  // Options passed straight to the SolardemoSDK constructor,
  // most usefully `base` to point at a server.
  sdk?: Record<string, any>

  // Run the SDK in offline test mode (in-memory mock transport).
  test?: boolean

  // Test feature options, e.g. {entity: {moon: {...}}} to
  // seed the mock with data. Only used when `test` is true.
  testopts?: Record<string, any>
}


function SolardemoProvider(this: any, options: SolardemoProviderOptions) {
  const seneca: any = this

  const entityBuilder = this.export('provider/entityBuilder')

  seneca.message('sys:provider,provider:solardemo,get:info', get_info)

  async function get_info(this: any, _msg: any) {
    return {
      ok: true,
      name: 'solardemo',
      version: Pkg.version,
      sdk: {
        name: '@voxgig-sdk/solardemo',
        version: SdkPkg.version,
      },
    }
  }


  // Every SDK operation resolves to an SDK ENTITY rather than raw data (a
  // removed record included: it comes back marked deleted, still holding what
  // it held). Seneca wants plain data, which the entity hands over through
  // data().
  function plain(res: any) {
    return null == res ? res : res.data()
  }


  // Seneca query directives (sort$, limit$, ...) are for the store, not the
  // API, so they must not reach the SDK as match fields.
  function cleanq(q: any) {
    const out: any = {}
    for (const k in (q || {})) {
      if (!k.endsWith('$')) {
        out[k] = q[k]
      }
    }
    return out
  }


  // The SDK throws on any non-2xx. A 404 from a single-item read is an
  // ordinary "not found" answer rather than a failure, so return null and let
  // everything else propagate. SDK errors carry the HTTP status at the top
  // level, so ask them rather than digging into `result`.
  async function ornull(action: () => Promise<any>) {
    try {
      return await action()
    }
    catch (e: any) {
      if (true === e?.notFound) {
        return null
      }
      throw e
    }
  }

  // Nested entities cannot build their path without the parent id, so
  // say which key is missing rather than letting the SDK report an opaque
  // 404 on a half-built URL.
  function need_moon_planet_id(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/solardemo-provider: moon ' + cmd + ': planet_id is required'
      )
    }
    return value
  }


  const entity: any = {
    moon: {
      cmd: {
        list: { action: (undefined as any) },
        load: { action: (undefined as any) },
        save: { action: (undefined as any) },
        remove: { action: (undefined as any) },
      },
    },

    planet: {
      cmd: {
        list: { action: (undefined as any) },
        load: { action: (undefined as any) },
        save: { action: (undefined as any) },
        remove: { action: (undefined as any) },
      },
    },

  }


  entity.moon.cmd.list.action =
    async function list_moon(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      need_moon_planet_id(q.planet_id, 'list')
      const list = await this.shared.sdk.Moon().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.moon.cmd.load.action =
    async function load_moon(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      need_moon_planet_id(q.planet_id, 'load')
      const res = await ornull(() => this.shared.sdk.Moon().load({ id: q.id, planet_id: q.planet_id }))
      return null == res ? null : entize(plain(res))
    }


  entity.moon.cmd.save.action =
    async function save_moon(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      need_moon_planet_id(data.planet_id, 'save')
      const sdk = this.shared.sdk

      const res = null == data.id
        ? await sdk.Moon().create(data)
        : await sdk.Moon().update(data)

      return entize(plain(res))
    }


  entity.moon.cmd.remove.action =
    async function remove_moon(this: any, _entize: any, msg: any) {
      const q = cleanq(msg.q)
      need_moon_planet_id(q.planet_id, 'remove')
      await ornull(() => this.shared.sdk.Moon().remove({ id: q.id, planet_id: q.planet_id }))
      return null
    }


  entity.planet.cmd.list.action =
    async function list_planet(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const list = await this.shared.sdk.Planet().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.planet.cmd.load.action =
    async function load_planet(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const res = await ornull(() => this.shared.sdk.Planet().load({ id: q.id }))
      return null == res ? null : entize(plain(res))
    }


  entity.planet.cmd.save.action =
    async function save_planet(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      const sdk = this.shared.sdk

      const res = null == data.id
        ? await sdk.Planet().create(data)
        : await sdk.Planet().update(data)

      return entize(plain(res))
    }


  entity.planet.cmd.remove.action =
    async function remove_planet(this: any, _entize: any, msg: any) {
      const q = cleanq(msg.q)
      await ornull(() => this.shared.sdk.Planet().remove({ id: q.id }))
      return null
    }


  entityBuilder(this, {
    provider: {
      name: 'solardemo',
    },
    entity
  })


  seneca.prepare(async function(this: any) {
    const sdkopts: any = Object.assign({}, options.sdk)

    // This API declares no authentication, so no credential is plumbed. The
    // SDK's auth stage emits nothing for an auth-inactive model and deletes
    // any `authorization` header regardless of options, so a keymap lookup
    // here would read a key that could not reach the wire — which is what the
    // first version of this target did.

    this.shared.sdk = options.test
      ? SolardemoSDK.test(options.testopts || {}, sdkopts)
      : new SolardemoSDK(sdkopts)
  })


  return {
    exports: {
      sdk: () => this.shared.sdk,
    },
  }
}


// Default options.
const defaults: SolardemoProviderOptions = {
  sdk: {},
  test: false,
  testopts: {},
}

Object.assign(SolardemoProvider, { defaults })

export default SolardemoProvider

if ('undefined' !== typeof module) {
  module.exports = SolardemoProvider
}
