/* Generated by @voxgig/sdkgen. Do not edit. */

const Pkg = require('../package.json')

const { VoxgigSolardemoSDK } = require('@voxgig-sdk/voxgig-solardemo-sdk')

const SdkPkg = require('@voxgig-sdk/voxgig-solardemo-sdk/package.json')


type VoxgigSolardemoProviderOptions = {
  // Options passed straight to the VoxgigSolardemoSDK constructor,
  // most usefully `base` to point at a server.
  sdk?: Record<string, any>

  // Run the SDK in offline test mode (in-memory mock transport).
  test?: boolean

  // Test feature options, e.g. {entity: {moon: {...}}} to
  // seed the mock with data. Only used when `test` is true.
  testopts?: Record<string, any>
}


function VoxgigSolardemoProvider(this: any, options: VoxgigSolardemoProviderOptions) {
  const seneca: any = this

  const entityBuilder = this.export('provider/entityBuilder')

  seneca.message('sys:provider,provider:voxgig-solardemo,get:info', get_info)

  async function get_info(this: any, _msg: any) {
    return {
      ok: true,
      name: 'voxgig-solardemo',
      version: Pkg.version,
      sdk: {
        name: '@voxgig-sdk/voxgig-solardemo-sdk',
        version: SdkPkg.version,
      },
    }
  }


  // Every SDK operation resolves to an SDK ENTITY rather than raw data (a
  // removed record included: it comes back marked deleted, still holding what
  // it held). Seneca wants plain data, which the entity hands over through
  // data().
  function plain(res: any) {
    return null == res ? res : res.data()
  }


  // Seneca query directives (sort$, limit$, ...) are for the store, not the
  // API, so they must not reach the SDK as match fields.
  function cleanq(q: any) {
    const out: any = {}
    for (const k in (q || {})) {
      if (!k.endsWith('$')) {
        out[k] = q[k]
      }
    }
    return out
  }


  // `action$` — the directive that selects a custom API action instead of
  // the plain cmd. READ BEFORE cleanq strips it, and still stripped from
  // what reaches the SDK as match fields: it is an instruction to the store,
  // like sort$ and limit$, not a value to filter on.
  //
  // THREE PLACES, because seneca-entity puts it in three places depending on
  // how the caller spelled it, and dropping any one of them silently turns a
  // named action into an ordinary call:
  //
  //   list$/load$/remove$({ action$ })         -> msg.q.action$
  //   ent.directive$({ action$ }).save$()      -> msg.action$
  //   const e = ent.make$({...}); e.action$=.. -> msg.ent.action$
  //
  // `make$({ action$ })` is NOT among them and cannot be: seneca-entity's
  // make$ copies only keys without a `$`, plus the four directives it knows
  // (id$, merge$, custom$, directive$), so an unknown trailing-`$` key is
  // dropped before any store sees it. `id$` reads like the precedent for
  // one, but it works only because make$ names it explicitly. The README
  // says so; there is nothing this plugin can check, because nothing arrives.
  function actionOf(msg: any) {
    const q = msg && msg.q
    const ent = msg && msg.ent

    return null != (q && q.action$) ? q.action$ :
      null != (msg && msg.action$) ? msg.action$ :
        null != (ent && ent.action$) ? ent.action$ :
          undefined
  }


  // The SDK argument for an ACTION on a read cmd: everything the caller sent
  // minus Seneca's own directives, with the id translated into the API's own
  // keys, plus the `$action` selector the SDK dispatches on.
  //
  // WIDER than the canonical argument on purpose. An action route has its own
  // parameters — GitHub's merge takes commit_title and merge_method, which the
  // canonical PATCH knows nothing about — so narrowing to the plain op's
  // required keys would strip the action's whole payload. The SDK still
  // validates: an action whose own point cannot be built is refused with
  // `point_action_invalid` rather than sent somewhere else.
  function actionq(q: any, action: string) {
    const out = cleanq(q)

    out.$action = action
    return out
  }


  // The SDK throws on any non-2xx. A 404 from a single-item read is an
  // ordinary "not found" answer rather than a failure, so return null and let
  // everything else propagate. SDK errors carry the HTTP status at the top
  // level, so ask them rather than digging into `result`.
  async function ornull(action: () => Promise<any>) {
    try {
      return await action()
    }
    catch (e: any) {
      if (true === e?.notFound) {
        return null
      }
      throw e
    }
  }

  // Nested entities cannot build their path without the parent id, so
  // say which key is missing rather than letting the SDK report an opaque
  // 404 on a half-built URL.
  function need_moon_planet_id(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/voxgig-solardemo-provider: moon ' + cmd + ': planet_id is required'
      )
    }

    // A path parameter is one value. A loaded record can carry an object
    // under the same name, and that must not be sent as a URL segment.
    if ('object' === typeof value) {
      throw new Error(
        '@seneca/voxgig-solardemo-provider: moon ' + cmd + ': planet_id must be a single ' +
        'value to build the request path, not an object'
      )
    }
    return value
  }


  // The custom actions each cmd can reach, as action -> SDK op. An action
  // is an alternative POINT of an ordinary op (`select.$action` in the API
  // model), so `save$` routes by this map rather than assuming update: an
  // action folded into `create` is reached through `save$` too.
  const ACTIONS: Record<string, Record<string, Record<string, string>>> = {
    ["moon"]: {
      list: {},
      load: {},
      save: {},
      remove: {},
    },
    ["planet"]: {
      list: {},
      load: {},
      save: { ["forbid"]: 'create', ["terraform"]: 'create' },
      remove: {},
    },
  }


  // Resolve an `action$` to the SDK op that serves it, or REFUSE it.
  //
  // Never falls through to the ordinary call. An action name the entity does
  // not have is a caller mistake worth a message that names what is
  // available; performing a plain save instead is the one outcome that must
  // not happen, because it succeeds and does the wrong thing.
  // AN OWN PROPERTY, never an inherited one. `map[name]` resolves
  // `toString`, `constructor`, `valueOf` and the rest off Object's
  // prototype, and each of those is non-null — so the refusal below never
  // fired and the inherited function was handed to the SDK as an op name.
  // That is the silent drop in another hat: the caller named something the
  // entity does not have and was not told. An empty map inherits them all,
  // so a cmd with no actions was the most exposed.
  // THE CMD THAT WOULD WRITE TO THE WRONG RESOURCE.
  //
  // Some entities gather their ops from unrelated routes, and then a cmd's
  // only route addresses something that is not this record: `migration`'s
  // remove deletes a repository's migration ARCHIVE, `user`'s deletes a GPG
  // KEY, `pull`'s deletes a review COMMENT. The id the caller passed is not
  // in the request at all.
  //
  // Such a cmd is refused rather than sent. A caller asking to remove one
  // record must not have a different resource deleted instead, and a
  // successful-looking reply is the worst possible answer. Where the real
  // operation exists it is reachable by name, through `action$`.
  function misaddressed(
    entname: string, cmd: string, key: string, addresses: string[]
  ) {
    const own = Object.prototype.hasOwnProperty
    const ents: any = own.call(ACTIONS, entname) ? ACTIONS[entname] : {}
    const acts = Object.keys(own.call(ents, cmd) ? ents[cmd] : {}).sort()

    throw new Error(
      '@seneca/voxgig-solardemo-provider: ' + entname + ' ' + cmd +
      ': this API has no ' + cmd + ' route for one ' + entname +
      '. Its only ' + cmd + ' route addresses ' + addresses.join(', ') +
      ', not ' + key + ', so the id would be ignored and a different record ' +
      'changed. ' +
      (0 < acts.length ?
        'Name the operation with action$ instead: ' + acts.join(', ') :
        'No action$ of this cmd is available either'))
  }


  function actionop(name: string, entname: string, cmd: string) {
    const own = Object.prototype.hasOwnProperty
    const ents: any = own.call(ACTIONS, entname) ? ACTIONS[entname] : {}
    const map: any = own.call(ents, cmd) ? ents[cmd] : {}
    const op = own.call(map, name) ? map[name] : null

    if (null == op) {
      const valid = Object.keys(map).sort()
      throw new Error(
        '@seneca/voxgig-solardemo-provider: ' + entname + ' ' + cmd + ': action$ "' + name +
        '" is not an action of this operation. Valid: ' +
        (0 < valid.length ? valid.join(', ') : '(none)'))
    }

    return op
  }


  const entity: any = {
    moon: {
      cmd: {
        list: { action: (undefined as any) },
        load: { action: (undefined as any) },
        save: { action: (undefined as any) },
        remove: { action: (undefined as any) },
      },
    },

    planet: {
      cmd: {
        list: { action: (undefined as any) },
        load: { action: (undefined as any) },
        save: { action: (undefined as any) },
        remove: { action: (undefined as any) },
      },
    },

  }


  entity.moon.cmd.list.action =
    async function list_moon(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'moon', 'list')
        const found = await this.shared.sdk.Moon()[op$](actionq(msg.q, action$))
        return found.map((data: any) => entize(plain(data)))
      }

      need_moon_planet_id(q.planet_id, 'list')
      const list = await this.shared.sdk.Moon().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.moon.cmd.load.action =
    async function load_moon(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'moon', 'load')
        const hit = await ornull(() => this.shared.sdk.Moon()[op$](actionq(msg.q, action$)))
        return null == hit ? null : entize(plain(hit))
      }

      need_moon_planet_id(q.planet_id, 'load')
      const res = await ornull(() => this.shared.sdk.Moon().load({ id: q.id, planet_id: q.planet_id }))
      return null == res ? null : entize(plain(res))
    }


  entity.moon.cmd.save.action =
    async function save_moon(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      const sdk = this.shared.sdk

      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'moon', 'save')
        // The action's OWN payload is the entity's own fields — data$(false)
        // has already dropped every trailing-`$` key, `action$` included,
        // so `$action` is the only thing added here.
        data.$action = action$
        const done = await sdk.Moon()[op$](data)
        return entize(plain(done))
      }

      let res
      if (null != data.id) {
        need_moon_planet_id(data.planet_id, 'save')
        res = await sdk.Moon().update(data)
      }
      else {
        need_moon_planet_id(data.planet_id, 'save')
        res = await sdk.Moon().create(data)
      }

      return entize(plain(res))
    }


  entity.moon.cmd.remove.action =
    async function remove_moon(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'moon', 'remove')
        const gone = await ornull(() => this.shared.sdk.Moon()[op$](actionq(msg.q, action$)))
        return null == gone ? null : entize(plain(gone))
      }

      need_moon_planet_id(q.planet_id, 'remove')
      await ornull(() => this.shared.sdk.Moon().remove({ id: q.id, planet_id: q.planet_id }))
      return null
    }


  entity.planet.cmd.list.action =
    async function list_planet(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'planet', 'list')
        const found = await this.shared.sdk.Planet()[op$](actionq(msg.q, action$))
        return found.map((data: any) => entize(plain(data)))
      }

      const list = await this.shared.sdk.Planet().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.planet.cmd.load.action =
    async function load_planet(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'planet', 'load')
        const hit = await ornull(() => this.shared.sdk.Planet()[op$](actionq(msg.q, action$)))
        return null == hit ? null : entize(plain(hit))
      }

      const res = await ornull(() => this.shared.sdk.Planet().load({ id: q.id }))
      return null == res ? null : entize(plain(res))
    }


  entity.planet.cmd.save.action =
    async function save_planet(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      const sdk = this.shared.sdk

      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'planet', 'save')
        // The action's OWN payload is the entity's own fields — data$(false)
        // has already dropped every trailing-`$` key, `action$` included,
        // so `$action` is the only thing added here.
        data.$action = action$
        const done = await sdk.Planet()[op$](data)
        return entize(plain(done))
      }

      let res
      if (null != data.id) {
        res = await sdk.Planet().update(data)
      }
      else {
        res = await sdk.Planet().create(data)
      }

      return entize(plain(res))
    }


  entity.planet.cmd.remove.action =
    async function remove_planet(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'planet', 'remove')
        const gone = await ornull(() => this.shared.sdk.Planet()[op$](actionq(msg.q, action$)))
        return null == gone ? null : entize(plain(gone))
      }

      await ornull(() => this.shared.sdk.Planet().remove({ id: q.id }))
      return null
    }


  entityBuilder(this, {
    provider: {
      name: 'voxgig-solardemo',
    },
    entity
  })


  seneca.prepare(async function(this: any) {
    const sdkopts: any = Object.assign({}, options.sdk)

    // This API declares no authentication, so no credential is plumbed. The
    // SDK's auth stage emits nothing for an auth-inactive model and deletes
    // any `authorization` header regardless of options, so a keymap lookup
    // here would read a key that could not reach the wire — which is what the
    // first version of this target did.

    this.shared.sdk = options.test
      ? VoxgigSolardemoSDK.test(options.testopts || {}, sdkopts)
      : new VoxgigSolardemoSDK(sdkopts)
  })


  return {
    exports: {
      sdk: () => this.shared.sdk,
    },
  }
}


// Default options.
const defaults: VoxgigSolardemoProviderOptions = {
  sdk: {},
  test: false,
  testopts: {},
}

Object.assign(VoxgigSolardemoProvider, { defaults })

export default VoxgigSolardemoProvider

if ('undefined' !== typeof module) {
  module.exports = VoxgigSolardemoProvider
}
