package voxgig.voxgigsolardemosdk.core;

import java.util.List;
import java.util.Map;

import voxgig.voxgigsolardemosdk.utility.Json;

/** Static SDK configuration and by-name feature construction. */
@SuppressWarnings({"unchecked"})
public final class Config {

  private Config() {}

  public static Map<String, Object> makeConfig() {
    return (Map<String, Object>) Json.parse(configJson());
  }

  // SHARED CONFIG (sdkgen rung L2).
  //
  // The SDK reads the config on every request and never writes to it, so one
  // instance is shared by every client rather than rebuilt per client - the
  // difference between parsing the embedded JSON once and once per client.
  //
  // Initialization-on-demand holder: the JLS guarantees the class initializer
  // runs once, lazily, and safely under concurrency, with no locking on the
  // read path.
  private static final class SharedHolder {
    static final Map<String, Object> VALUE = makeConfig();
  }

  // The process-wide config, built once on first use.
  //
  // The returned map is SHARED: treat it as read-only. Callers that need to
  // mutate should use makeConfig, which always parses a fresh copy.
  public static Map<String, Object> sharedConfig() {
    return SharedHolder.VALUE;
  }

  public static Feature makeFeature(String name) {
    switch (name) {
      case "debug":
        return new voxgig.voxgigsolardemosdk.feature.DebugFeature();
      case "idempotency":
        return new voxgig.voxgigsolardemosdk.feature.IdempotencyFeature();
      case "metrics":
        return new voxgig.voxgigsolardemosdk.feature.MetricsFeature();
      case "paging":
        return new voxgig.voxgigsolardemosdk.feature.PagingFeature();
      case "ratelimit":
        return new voxgig.voxgigsolardemosdk.feature.RatelimitFeature();
      case "retry":
        return new voxgig.voxgigsolardemosdk.feature.RetryFeature();
      case "secrets":
        return new voxgig.voxgigsolardemosdk.feature.SecretsFeature();
      case "test":
        return new voxgig.voxgigsolardemosdk.feature.TestFeature();
      case "timeout":
        return new voxgig.voxgigsolardemosdk.feature.TimeoutFeature();
      default:
        return new voxgig.voxgigsolardemosdk.feature.BaseFeature();
    }
  }

  /**
   * The plugin definitions the model selected for one feature's chain, as
   * List&lt;Object&gt; so core never names a vendored type. Empty for a
   * feature whose model declares no active plugin group.
   */
  public static List<Object> featurePlugins(String name) {
    switch (name) {
      default:
        return List.of();
    }
  }

  private static String configJson() {
    StringBuilder b = new StringBuilder();
    b.append("{");
    b.append(" \"main\": {");
    b.append("  \"name\": \"VoxgigSolardemo\",");
    b.append("  \"slug\": \"voxgig-solardemo\",");
    b.append("  \"version\": \"0.1.0\",");
    b.append("  \"target\": \"java\"");
    b.append(" },");
    b.append(" \"feature\": {");
    b.append("  \"debug\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"max\": 100,");
    b.append("    \"redact\": [");
    b.append("     \"authorization\",");
    b.append("     \"cookie\",");
    b.append("     \"set-cookie\",");
    b.append("     \"api-key\",");
    b.append("     \"apikey\",");
    b.append("     \"x-api-key\",");
    b.append("     \"idempotency-key\"");
    b.append("    ]");
    b.append("   },");
    b.append("   \"optspec\": {");
    b.append("    \"now\": \"`$FUNCTION`\",");
    b.append("    \"onEntry\": \"`$FUNCTION`\"");
    b.append("   },");
    b.append("   \"strict\": false,");
    b.append("   \"transport\": \"none\"");
    b.append("  },");
    b.append("  \"idempotency\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"header\": \"Idempotency-Key\",");
    b.append("    \"methods\": [");
    b.append("     \"POST\",");
    b.append("     \"PUT\",");
    b.append("     \"PATCH\",");
    b.append("     \"DELETE\"");
    b.append("    ],");
    b.append("    \"ops\": [");
    b.append("     \"create\",");
    b.append("     \"update\",");
    b.append("     \"remove\"");
    b.append("    ]");
    b.append("   },");
    b.append("   \"optspec\": {");
    b.append("    \"keygen\": \"`$FUNCTION`\"");
    b.append("   },");
    b.append("   \"strict\": false,");
    b.append("   \"transport\": \"none\"");
    b.append("  },");
    b.append("  \"metrics\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false");
    b.append("   },");
    b.append("   \"optspec\": {");
    b.append("    \"now\": \"`$FUNCTION`\"");
    b.append("   },");
    b.append("   \"strict\": false,");
    b.append("   \"transport\": \"none\"");
    b.append("  },");
    b.append("  \"paging\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"afterVar\": \"after\",");
    b.append("    \"cursorParam\": \"cursor\",");
    b.append("    \"firstVar\": \"first\",");
    b.append("    \"limitParam\": \"limit\",");
    b.append("    \"pageParam\": \"page\",");
    b.append("    \"startPage\": 1");
    b.append("   },");
    b.append("   \"optspec\": {");
    b.append("    \"limit\": \"`$NUMBER`\",");
    b.append("    \"ops\": \"`$LIST`\"");
    b.append("   },");
    b.append("   \"strict\": false,");
    b.append("   \"transport\": \"none\"");
    b.append("  },");
    b.append("  \"ratelimit\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"burst\": 5,");
    b.append("    \"rate\": 5");
    b.append("   },");
    b.append("   \"optspec\": {");
    b.append("    \"now\": \"`$FUNCTION`\",");
    b.append("    \"sleep\": \"`$FUNCTION`\"");
    b.append("   },");
    b.append("   \"strict\": false,");
    b.append("   \"transport\": \"wrap\"");
    b.append("  },");
    b.append("  \"retry\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"factor\": 2,");
    b.append("    \"maxDelay\": 2000,");
    b.append("    \"minDelay\": 50,");
    b.append("    \"retries\": 2,");
    b.append("    \"statuses\": [");
    b.append("     408,");
    b.append("     425,");
    b.append("     429,");
    b.append("     500,");
    b.append("     502,");
    b.append("     503,");
    b.append("     504");
    b.append("    ]");
    b.append("   },");
    b.append("   \"optspec\": {");
    b.append("    \"jitter\": \"`$BOOLEAN`\",");
    b.append("    \"sleep\": \"`$FUNCTION`\"");
    b.append("   },");
    b.append("   \"strict\": false,");
    b.append("   \"transport\": \"wrap\"");
    b.append("  },");
    b.append("  \"secrets\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"cache\": true,");
    b.append("    \"exchange\": {");
    b.append("     \"active\": false,");
    b.append("     \"method\": \"POST\",");
    b.append("     \"path\": \"auth/token\",");
    b.append("     \"refresh\": \"\",");
    b.append("     \"request\": \"refresh_token\",");
    b.append("     \"response\": \"access_token\",");
    b.append("     \"retries\": 1,");
    b.append("     \"statuses\": [");
    b.append("      401");
    b.append("     ]");
    b.append("    },");
    b.append("    \"name\": \"apikey\",");
    b.append("    \"providers\": []");
    b.append("   },");
    b.append("   \"optspec\": {},");
    b.append("   \"strict\": false,");
    b.append("   \"transport\": \"wrap\"");
    b.append("  },");
    b.append("  \"test\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false");
    b.append("   },");
    b.append("   \"optspec\": {");
    b.append("    \"entity\": \"`$MAP`\",");
    b.append("    \"net\": \"`$MAP`\"");
    b.append("   },");
    b.append("   \"strict\": false,");
    b.append("   \"transport\": \"base\"");
    b.append("  },");
    b.append("  \"timeout\": {");
    b.append("   \"options\": {");
    b.append("    \"active\": false,");
    b.append("    \"ms\": 30000");
    b.append("   },");
    b.append("   \"optspec\": {");
    b.append("    \"clearTimer\": \"`$FUNCTION`\",");
    b.append("    \"setTimer\": \"`$FUNCTION`\"");
    b.append("   },");
    b.append("   \"strict\": false,");
    b.append("   \"transport\": \"wrap\"");
    b.append("  }");
    b.append(" },");
    b.append(" \"options\": {");
    b.append("  \"base\": \"http://localhost:8901\",");
    b.append("  \"headers\": {");
    b.append("   \"content-type\": \"application/json\"");
    b.append("  },");
    b.append("  \"entity\": {");
    b.append("   \"moon\": {},");
    b.append("   \"planet\": {}");
    b.append("  }");
    b.append(" },");
    b.append(" \"entity\": {");
    b.append("  \"moon\": {");
    b.append("   \"fields\": [");
    b.append("    {");
    b.append("     \"name\": \"diameter\",");
    b.append("     \"title\": \"Diameter\",");
    b.append("     \"type\": \"`$NUMBER`\",");
    b.append("     \"req\": true,");
    b.append("     \"format\": \"float\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"id\",");
    b.append("     \"title\": \"Id\",");
    b.append("     \"type\": \"`$STRING`\",");
    b.append("     \"req\": true");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"kind\",");
    b.append("     \"title\": \"Kind\",");
    b.append("     \"type\": \"`$STRING`\",");
    b.append("     \"req\": true");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"name\",");
    b.append("     \"title\": \"Name\",");
    b.append("     \"type\": \"`$STRING`\",");
    b.append("     \"req\": true");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"planet_id\",");
    b.append("     \"title\": \"Planet Id\",");
    b.append("     \"type\": \"`$STRING`\",");
    b.append("     \"req\": true");
    b.append("    }");
    b.append("   ],");
    b.append("   \"id\": {");
    b.append("    \"field\": \"id\",");
    b.append("    \"name\": \"id\"");
    b.append("   },");
    b.append("   \"name\": \"moon\",");
    b.append("   \"op\": {");
    b.append("    \"create\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"create\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"POST\",");
    b.append("       \"orig\": \"/api/planet/{planet_id}/moon\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"api\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"planet\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"planet_id\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"moon\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"parts\": [");
    b.append("        \"api\",");
    b.append("        \"planet\",");
    b.append("        \"{planet_id}\",");
    b.append("        \"moon\"");
    b.append("       ],");
    b.append("       \"rename\": {},");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       },");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"name\": \"planet_id\",");
    b.append("          \"orig\": \"planet_id\",");
    b.append("          \"type\": \"`$STRING`\",");
    b.append("          \"kind\": \"param\",");
    b.append("          \"reqd\": true");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"select\": {");
    b.append("        \"exist\": [");
    b.append("         \"planet_id\"");
    b.append("        ]");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    },");
    b.append("    \"list\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"list\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"GET\",");
    b.append("       \"orig\": \"/api/planet/{planet_id}/moon\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"api\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"planet\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"planet_id\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"moon\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"parts\": [");
    b.append("        \"api\",");
    b.append("        \"planet\",");
    b.append("        \"{planet_id}\",");
    b.append("        \"moon\"");
    b.append("       ],");
    b.append("       \"rename\": {},");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       },");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"name\": \"planet_id\",");
    b.append("          \"orig\": \"planet_id\",");
    b.append("          \"type\": \"`$STRING`\",");
    b.append("          \"kind\": \"param\",");
    b.append("          \"reqd\": true");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"select\": {");
    b.append("        \"exist\": [");
    b.append("         \"planet_id\"");
    b.append("        ]");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    },");
    b.append("    \"load\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"load\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"GET\",");
    b.append("       \"orig\": \"/api/planet/{planet_id}/moon/{moon_id}\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"api\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"planet\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"planet_id\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"moon\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"id\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"parts\": [");
    b.append("        \"api\",");
    b.append("        \"planet\",");
    b.append("        \"{planet_id}\",");
    b.append("        \"moon\",");
    b.append("        \"{id}\"");
    b.append("       ],");
    b.append("       \"rename\": {");
    b.append("        \"param\": {");
    b.append("         \"moon_id\": \"id\"");
    b.append("        }");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       },");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"name\": \"id\",");
    b.append("          \"orig\": \"moon_id\",");
    b.append("          \"type\": \"`$STRING`\",");
    b.append("          \"kind\": \"param\",");
    b.append("          \"reqd\": true");
    b.append("         },");
    b.append("         {");
    b.append("          \"name\": \"planet_id\",");
    b.append("          \"orig\": \"planet_id\",");
    b.append("          \"type\": \"`$STRING`\",");
    b.append("          \"kind\": \"param\",");
    b.append("          \"reqd\": true");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"select\": {");
    b.append("        \"exist\": [");
    b.append("         \"id\",");
    b.append("         \"planet_id\"");
    b.append("        ]");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    },");
    b.append("    \"remove\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"remove\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"DELETE\",");
    b.append("       \"orig\": \"/api/planet/{planet_id}/moon/{moon_id}\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"api\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"planet\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"planet_id\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"moon\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"id\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"parts\": [");
    b.append("        \"api\",");
    b.append("        \"planet\",");
    b.append("        \"{planet_id}\",");
    b.append("        \"moon\",");
    b.append("        \"{id}\"");
    b.append("       ],");
    b.append("       \"rename\": {");
    b.append("        \"param\": {");
    b.append("         \"moon_id\": \"id\"");
    b.append("        }");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       },");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"name\": \"id\",");
    b.append("          \"orig\": \"moon_id\",");
    b.append("          \"type\": \"`$STRING`\",");
    b.append("          \"kind\": \"param\",");
    b.append("          \"reqd\": true");
    b.append("         },");
    b.append("         {");
    b.append("          \"name\": \"planet_id\",");
    b.append("          \"orig\": \"planet_id\",");
    b.append("          \"type\": \"`$STRING`\",");
    b.append("          \"kind\": \"param\",");
    b.append("          \"reqd\": true");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"select\": {");
    b.append("        \"exist\": [");
    b.append("         \"id\",");
    b.append("         \"planet_id\"");
    b.append("        ]");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    },");
    b.append("    \"update\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"update\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"PUT\",");
    b.append("       \"orig\": \"/api/planet/{planet_id}/moon/{moon_id}\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"api\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"planet\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"planet_id\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"moon\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"id\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"parts\": [");
    b.append("        \"api\",");
    b.append("        \"planet\",");
    b.append("        \"{planet_id}\",");
    b.append("        \"moon\",");
    b.append("        \"{id}\"");
    b.append("       ],");
    b.append("       \"rename\": {");
    b.append("        \"param\": {");
    b.append("         \"moon_id\": \"id\"");
    b.append("        }");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       },");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"name\": \"id\",");
    b.append("          \"orig\": \"moon_id\",");
    b.append("          \"type\": \"`$STRING`\",");
    b.append("          \"kind\": \"param\",");
    b.append("          \"reqd\": true");
    b.append("         },");
    b.append("         {");
    b.append("          \"name\": \"planet_id\",");
    b.append("          \"orig\": \"planet_id\",");
    b.append("          \"type\": \"`$STRING`\",");
    b.append("          \"kind\": \"param\",");
    b.append("          \"reqd\": true");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"select\": {");
    b.append("        \"exist\": [");
    b.append("         \"id\",");
    b.append("         \"planet_id\"");
    b.append("        ]");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    }");
    b.append("   },");
    b.append("   \"relations\": {");
    b.append("    \"ancestors\": [");
    b.append("     [");
    b.append("      \"$.main.kit.entity.planet\"");
    b.append("     ]");
    b.append("    ]");
    b.append("   }");
    b.append("  },");
    b.append("  \"planet\": {");
    b.append("   \"fields\": [");
    b.append("    {");
    b.append("     \"name\": \"diameter\",");
    b.append("     \"title\": \"Diameter\",");
    b.append("     \"type\": \"`$NUMBER`\",");
    b.append("     \"req\": true,");
    b.append("     \"format\": \"float\"");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"forbidReason\",");
    b.append("     \"title\": \"Forbid Reason\",");
    b.append("     \"type\": \"`$STRING`\",");
    b.append("     \"short\": \"Why the planet is forbidden, carried from the forbid action's `why`.\",");
    b.append("     \"readOnly\": true");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"forbidState\",");
    b.append("     \"title\": \"Forbid State\",");
    b.append("     \"type\": \"`$STRING`\",");
    b.append("     \"short\": \"Set by the forbid action, and absent until it first runs.\",");
    b.append("     \"readOnly\": true");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"id\",");
    b.append("     \"title\": \"Id\",");
    b.append("     \"type\": \"`$STRING`\",");
    b.append("     \"req\": true");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"kind\",");
    b.append("     \"title\": \"Kind\",");
    b.append("     \"type\": \"`$STRING`\",");
    b.append("     \"req\": true");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"name\",");
    b.append("     \"title\": \"Name\",");
    b.append("     \"type\": \"`$STRING`\",");
    b.append("     \"req\": true");
    b.append("    },");
    b.append("    {");
    b.append("     \"name\": \"terraformState\",");
    b.append("     \"title\": \"Terraform State\",");
    b.append("     \"type\": \"`$STRING`\",");
    b.append("     \"short\": \"Set by the terraform action, and absent until it first runs.\",");
    b.append("     \"readOnly\": true");
    b.append("    }");
    b.append("   ],");
    b.append("   \"id\": {");
    b.append("    \"field\": \"id\",");
    b.append("    \"name\": \"id\"");
    b.append("   },");
    b.append("   \"name\": \"planet\",");
    b.append("   \"op\": {");
    b.append("    \"create\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"create\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"POST\",");
    b.append("       \"orig\": \"/api/planet/{planet_id}/forbid\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"api\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"planet\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"id\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"forbid\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"parts\": [");
    b.append("        \"api\",");
    b.append("        \"planet\",");
    b.append("        \"{id}\",");
    b.append("        \"forbid\"");
    b.append("       ],");
    b.append("       \"rename\": {");
    b.append("        \"param\": {");
    b.append("         \"planet_id\": \"id\"");
    b.append("        }");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       },");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"name\": \"id\",");
    b.append("          \"orig\": \"planet_id\",");
    b.append("          \"type\": \"`$STRING`\",");
    b.append("          \"kind\": \"param\",");
    b.append("          \"reqd\": true");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"select\": {");
    b.append("        \"$action\": \"forbid\",");
    b.append("        \"exist\": [");
    b.append("         \"id\"");
    b.append("        ]");
    b.append("       }");
    b.append("      },");
    b.append("      {");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"POST\",");
    b.append("       \"orig\": \"/api/planet/{planet_id}/terraform\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"api\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"planet\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"id\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"terraform\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"parts\": [");
    b.append("        \"api\",");
    b.append("        \"planet\",");
    b.append("        \"{id}\",");
    b.append("        \"terraform\"");
    b.append("       ],");
    b.append("       \"rename\": {");
    b.append("        \"param\": {");
    b.append("         \"planet_id\": \"id\"");
    b.append("        }");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       },");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"name\": \"id\",");
    b.append("          \"orig\": \"planet_id\",");
    b.append("          \"type\": \"`$STRING`\",");
    b.append("          \"kind\": \"param\",");
    b.append("          \"reqd\": true");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"select\": {");
    b.append("        \"$action\": \"terraform\",");
    b.append("        \"exist\": [");
    b.append("         \"id\"");
    b.append("        ]");
    b.append("       }");
    b.append("      },");
    b.append("      {");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"POST\",");
    b.append("       \"orig\": \"/api/planet\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"api\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"planet\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"parts\": [");
    b.append("        \"api\",");
    b.append("        \"planet\"");
    b.append("       ],");
    b.append("       \"rename\": {},");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       },");
    b.append("       \"args\": {},");
    b.append("       \"select\": {}");
    b.append("      }");
    b.append("     ]");
    b.append("    },");
    b.append("    \"list\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"list\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"GET\",");
    b.append("       \"orig\": \"/api/planet\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"api\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"planet\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"parts\": [");
    b.append("        \"api\",");
    b.append("        \"planet\"");
    b.append("       ],");
    b.append("       \"rename\": {},");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       },");
    b.append("       \"args\": {},");
    b.append("       \"select\": {}");
    b.append("      }");
    b.append("     ]");
    b.append("    },");
    b.append("    \"load\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"load\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"GET\",");
    b.append("       \"orig\": \"/api/planet/{planet_id}\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"api\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"planet\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"id\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"parts\": [");
    b.append("        \"api\",");
    b.append("        \"planet\",");
    b.append("        \"{id}\"");
    b.append("       ],");
    b.append("       \"rename\": {");
    b.append("        \"param\": {");
    b.append("         \"planet_id\": \"id\"");
    b.append("        }");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       },");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"name\": \"id\",");
    b.append("          \"orig\": \"planet_id\",");
    b.append("          \"type\": \"`$STRING`\",");
    b.append("          \"kind\": \"param\",");
    b.append("          \"reqd\": true");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"select\": {");
    b.append("        \"exist\": [");
    b.append("         \"id\"");
    b.append("        ]");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    },");
    b.append("    \"remove\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"remove\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"DELETE\",");
    b.append("       \"orig\": \"/api/planet/{planet_id}\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"api\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"planet\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"id\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"parts\": [");
    b.append("        \"api\",");
    b.append("        \"planet\",");
    b.append("        \"{id}\"");
    b.append("       ],");
    b.append("       \"rename\": {");
    b.append("        \"param\": {");
    b.append("         \"planet_id\": \"id\"");
    b.append("        }");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       },");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"name\": \"id\",");
    b.append("          \"orig\": \"planet_id\",");
    b.append("          \"type\": \"`$STRING`\",");
    b.append("          \"kind\": \"param\",");
    b.append("          \"reqd\": true");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"select\": {");
    b.append("        \"exist\": [");
    b.append("         \"id\"");
    b.append("        ]");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    },");
    b.append("    \"update\": {");
    b.append("     \"input\": \"data\",");
    b.append("     \"name\": \"update\",");
    b.append("     \"points\": [");
    b.append("      {");
    b.append("       \"kind\": \"http\",");
    b.append("       \"method\": \"PUT\",");
    b.append("       \"orig\": \"/api/planet/{planet_id}\",");
    b.append("       \"segments\": [");
    b.append("        {");
    b.append("         \"lit\": \"api\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"lit\": \"planet\"");
    b.append("        },");
    b.append("        {");
    b.append("         \"var\": \"id\"");
    b.append("        }");
    b.append("       ],");
    b.append("       \"parts\": [");
    b.append("        \"api\",");
    b.append("        \"planet\",");
    b.append("        \"{id}\"");
    b.append("       ],");
    b.append("       \"rename\": {");
    b.append("        \"param\": {");
    b.append("         \"planet_id\": \"id\"");
    b.append("        }");
    b.append("       },");
    b.append("       \"transform\": {");
    b.append("        \"req\": \"`reqdata`\",");
    b.append("        \"res\": \"`body`\"");
    b.append("       },");
    b.append("       \"args\": {");
    b.append("        \"params\": [");
    b.append("         {");
    b.append("          \"name\": \"id\",");
    b.append("          \"orig\": \"planet_id\",");
    b.append("          \"type\": \"`$STRING`\",");
    b.append("          \"kind\": \"param\",");
    b.append("          \"reqd\": true");
    b.append("         }");
    b.append("        ]");
    b.append("       },");
    b.append("       \"select\": {");
    b.append("        \"exist\": [");
    b.append("         \"id\"");
    b.append("        ]");
    b.append("       }");
    b.append("      }");
    b.append("     ]");
    b.append("    }");
    b.append("   },");
    b.append("   \"relations\": {");
    b.append("    \"ancestors\": []");
    b.append("   }");
    b.append("  }");
    b.append(" }");
    b.append("}");
    return b.toString();
  }
}
