# Solardemo Data — notebook-friendly access to the Solardemo API.
#
# GENERATED by @voxgig/sdkgen (py-data target). Edits are overwritten.

from __future__ import annotations

from typing import Any

import pandas as pd

from . import auth
from .entity_frames import EntityFrames
from .frames import records_df

# The sibling SDK is a separate distribution, so this import stays absolute.
from solardemo_sdk import SolardemoSDK


class SolardemoData(EntityFrames):
    """Solardemo API as pandas DataFrames.

    Wraps — never subclasses — the SolardemoSDK client. The wrapped client is
    available as `.sdk` for the cases this package deliberately does not
    cover (writes, non-entity endpoints, per-call control).
    """

    def __init__(self, sdk: SolardemoSDK, base_url: str | None = None):
        self.sdk = sdk
        self.base_url = base_url

    # ---- escape hatches ---------------------------------------------------

    def frame(self, result: Any, **kwargs) -> pd.DataFrame:
        """Shape ANY op result into a DataFrame.

        For endpoints without a generated accessor:

            rows = ad.sdk.SomeEntity().list()
            df = ad.frame(rows)
        """
        return records_df(result, **kwargs)

    def entities(self) -> list:
        """The entity accessors available on this object."""
        return sorted(self._ACCESSORS)

    def _repr_html_(self) -> str:
        accessors = "".join(
            f"<li><code>{a}()</code></li>" for a in sorted(self._ACCESSORS))
        base = self.base_url or "(default)"
        return (
            f"<b>SolardemoData</b><br>"
            f"<small>base: <code>{base}</code></small>"
            f"<ul>{accessors}</ul>"
        )

    def __repr__(self) -> str:
        return (f"<SolardemoData base={self.base_url or '(default)'} "
                f"accessors={len(self._ACCESSORS)}>")


def data(
    token: str | None = None,
    base_url: str | None = None,
    **options,
) -> SolardemoData:
    """Build a SolardemoData client, finding credentials automatically.

    Discovery order (first hit wins):
      1. the `token` / `base_url` arguments
      2. Colab secrets  — SOLARDEMO_APIKEY / SOLARDEMO_BASE
      3. environment    — SOLARDEMO_APIKEY / SOLARDEMO_BASE

    Extra keyword arguments are passed straight through to the SDK client, so
    anything the SDK accepts (feature options, headers, timeouts) works here.
    """
    token, base_url, _source = auth.resolve("SOLARDEMO", token, base_url)

    if not token:
        raise ValueError(auth.missing_token_message("SOLARDEMO"))

    opts: dict = {"apikey": token}
    if base_url:
        opts["base"] = base_url
    opts.update(options)

    return SolardemoData(SolardemoSDK(opts), base_url)
