# solardemo data — generated entity accessors.
#
# GENERATED by @voxgig/sdkgen (py-data target). Edits are overwritten.
#
# One accessor per entity. Column names and dtypes come from the API model,
# so `ad.<tab>` and `ad.thing?` replace a trip to the reference docs.

from __future__ import annotations

import pandas as pd

from .fetch import drain, MAX_PAGES_DEFAULT
from .frames import build_frame, to_series, FLATTEN_DEFAULT


class EntityFrames:
    """Mixin carrying the generated accessors. Mixed into <Name>Data."""

    _ACCESSORS = [
        "moons",
        "planets",
        "moon",
        "planet",
    ]

    def moons(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All moon records as a DataFrame.

        Columns:
          diameter (Float64, required)
          id (string, required)
          kind (string, required)
          name (string, required)
          planet_id (string, required)

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.Moon()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={
                "diameter": "Float64",
                "id": "string",
                "kind": "string",
                "name": "string",
                "planet_id": "string",
            },
            order=[
                "diameter",
                "id",
                "kind",
                "name",
                "planet_id",
            ],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def planets(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All planet records as a DataFrame.

        Columns:
          diameter (Float64, required)
          forbid (boolean)
          id (string, required)
          kind (string, required)
          name (string, required)
          ok (boolean)
          start (boolean)
          state (string)
          stop (boolean)
          why (string)

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.Planet()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={
                "diameter": "Float64",
                "forbid": "boolean",
                "id": "string",
                "kind": "string",
                "name": "string",
                "ok": "boolean",
                "start": "boolean",
                "state": "string",
                "stop": "boolean",
                "why": "string",
            },
            order=[
                "diameter",
                "forbid",
                "id",
                "kind",
                "name",
                "ok",
                "start",
                "state",
                "stop",
                "why",
            ],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def moon(
        self,
        id,
        *,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
    ) -> pd.Series:
        """One moon record, by id, as a Series.

        Columns:
          diameter (Float64, required)
          id (string, required)
          kind (string, required)
          name (string, required)
          planet_id (string, required)
        """
        rec = self.sdk.Moon().load({"id": id})
        return to_series(
            rec,
            dtypes={
                "diameter": "Float64",
                "id": "string",
                "kind": "string",
                "name": "string",
                "planet_id": "string",
            },
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def planet(
        self,
        id,
        *,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
    ) -> pd.Series:
        """One planet record, by id, as a Series.

        Columns:
          diameter (Float64, required)
          forbid (boolean)
          id (string, required)
          kind (string, required)
          name (string, required)
          ok (boolean)
          start (boolean)
          state (string)
          stop (boolean)
          why (string)
        """
        rec = self.sdk.Planet().load({"id": id})
        return to_series(
            rec,
            dtypes={
                "diameter": "Float64",
                "forbid": "boolean",
                "id": "string",
                "kind": "string",
                "name": "string",
                "ok": "boolean",
                "start": "boolean",
                "state": "string",
                "stop": "boolean",
                "why": "string",
            },
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )
