;; Solardemo SDK public API (generated by @voxgig/sdkgen).
(ns sdk.api
  (:require [sdk.client :as client]
            [sdk.entity.moon :as e-moon]
            [sdk.entity.planet :as e-planet]))

(def make-sdk client/make-sdk)
(def test-sdk client/test-sdk)
(def direct client/direct)
(def graphql client/graphql)
(def prepare client/prepare)
(def options-map client/options-map)

;; Moon accessor: (moon client data)
(defn moon [client data] (e-moon/make client data))

;; Planet accessor: (planet client data)
(defn planet [client data] (e-planet/make client data))
