;; VoxgigSolardemo SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]
            [sdk.feature.secrets :as fx-secrets]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "moon" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "format" "float"
            "name" "diameter"
            "req" true
            "title" "Diameter"
            "type" "`$NUMBER`")
          (vs/jm
            "name" "id"
            "req" true
            "title" "Id"
            "type" "`$STRING`")
          (vs/jm
            "name" "kind"
            "req" true
            "title" "Kind"
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "req" true
            "title" "Name"
            "type" "`$STRING`")
          (vs/jm
            "name" "planet_id"
            "req" true
            "title" "Planet Id"
            "type" "`$STRING`"))
        "id" (vs/jm
          "field" "id"
          "name" "id")
        "name" "moon"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "planet_id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/api/planet/{planet_id}/moon"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{planet_id}"
                  "moon")
                "rename" (vs/jm)
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "planet_id")
                  (vs/jm
                    "lit" "moon"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "planet_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "planet_id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/api/planet/{planet_id}/moon"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{planet_id}"
                  "moon")
                "rename" (vs/jm)
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "planet_id")
                  (vs/jm
                    "lit" "moon"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "planet_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "moon_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "param"
                      "name" "planet_id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/api/planet/{planet_id}/moon/{moon_id}"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{planet_id}"
                  "moon"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "moon_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "planet_id")
                  (vs/jm
                    "lit" "moon")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"
                    "planet_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "moon_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "param"
                      "name" "planet_id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "DELETE"
                "orig" "/api/planet/{planet_id}/moon/{moon_id}"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{planet_id}"
                  "moon"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "moon_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "planet_id")
                  (vs/jm
                    "lit" "moon")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"
                    "planet_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "update" (vs/jm
            "input" "data"
            "name" "update"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "moon_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "param"
                      "name" "planet_id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "PUT"
                "orig" "/api/planet/{planet_id}/moon/{moon_id}"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{planet_id}"
                  "moon"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "moon_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "planet_id")
                  (vs/jm
                    "lit" "moon")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"
                    "planet_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "$.main.kit.entity.planet"))))
      "planet" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "format" "float"
            "name" "diameter"
            "req" true
            "title" "Diameter"
            "type" "`$NUMBER`")
          (vs/jm
            "name" "forbidReason"
            "readOnly" true
            "short" "Why the planet is forbidden, carried from the forbid action's `why`."
            "title" "Forbid Reason"
            "type" "`$STRING`")
          (vs/jm
            "name" "forbidState"
            "readOnly" true
            "short" "Set by the forbid action, and absent until it first runs."
            "title" "Forbid State"
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "req" true
            "title" "Id"
            "type" "`$STRING`")
          (vs/jm
            "name" "kind"
            "req" true
            "title" "Kind"
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "req" true
            "title" "Name"
            "type" "`$STRING`")
          (vs/jm
            "name" "terraformState"
            "readOnly" true
            "short" "Set by the terraform action, and absent until it first runs."
            "title" "Terraform State"
            "type" "`$STRING`"))
        "id" (vs/jm
          "field" "id"
          "name" "id")
        "name" "planet"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/api/planet/{planet_id}/forbid"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{id}"
                  "forbid")
                "rename" (vs/jm
                  "param" (vs/jm
                    "planet_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "id")
                  (vs/jm
                    "lit" "forbid"))
                "select" (vs/jm
                  "$action" "forbid"
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/api/planet/{planet_id}/terraform"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{id}"
                  "terraform")
                "rename" (vs/jm
                  "param" (vs/jm
                    "planet_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "id")
                  (vs/jm
                    "lit" "terraform"))
                "select" (vs/jm
                  "$action" "terraform"
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/api/planet"
                "parts" (vs/jt
                  "api"
                  "planet")
                "rename" (vs/jm)
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet"))
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/api/planet"
                "parts" (vs/jt
                  "api"
                  "planet")
                "rename" (vs/jm)
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet"))
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/api/planet/{planet_id}"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "planet_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "DELETE"
                "orig" "/api/planet/{planet_id}"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "planet_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "update" (vs/jm
            "input" "data"
            "name" "update"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "PUT"
                "orig" "/api/planet/{planet_id}"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "planet_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt))))
    "feature" (vs/jm
      "debug" (vs/jm
        "options" (vs/jm
          "active" false
          "max" 100
          "redact" (vs/jt
            "authorization"
            "cookie"
            "set-cookie"
            "api-key"
            "apikey"
            "x-api-key"
            "idempotency-key"))
        "optspec" (vs/jm
          "now" "`$FUNCTION`"
          "onEntry" "`$FUNCTION`")
        "strict" false
        "transport" "none")
      "idempotency" (vs/jm
        "options" (vs/jm
          "active" false
          "header" "Idempotency-Key"
          "methods" (vs/jt
            "POST"
            "PUT"
            "PATCH"
            "DELETE")
          "ops" (vs/jt
            "create"
            "update"
            "remove"))
        "optspec" (vs/jm
          "keygen" "`$FUNCTION`")
        "strict" false
        "transport" "none")
      "metrics" (vs/jm
        "options" (vs/jm
          "active" false)
        "optspec" (vs/jm
          "now" "`$FUNCTION`")
        "strict" false
        "transport" "none")
      "paging" (vs/jm
        "options" (vs/jm
          "active" false
          "afterVar" "after"
          "cursorParam" "cursor"
          "firstVar" "first"
          "limitParam" "limit"
          "pageParam" "page"
          "startPage" 1)
        "optspec" (vs/jm
          "limit" "`$NUMBER`"
          "ops" "`$LIST`")
        "strict" false
        "transport" "none")
      "ratelimit" (vs/jm
        "options" (vs/jm
          "active" false
          "burst" 5
          "rate" 5)
        "optspec" (vs/jm
          "now" "`$FUNCTION`"
          "sleep" "`$FUNCTION`")
        "strict" false
        "transport" "wrap")
      "retry" (vs/jm
        "options" (vs/jm
          "active" false
          "factor" 2
          "maxDelay" 2000
          "minDelay" 50
          "retries" 2
          "statuses" (vs/jt
            408
            425
            429
            500
            502
            503
            504))
        "optspec" (vs/jm
          "jitter" "`$BOOLEAN`"
          "sleep" "`$FUNCTION`")
        "strict" false
        "transport" "wrap")
      "secrets" (vs/jm
        "options" (vs/jm
          "active" false
          "cache" true
          "exchange" (vs/jm
            "active" false
            "method" "POST"
            "path" "auth/token"
            "refresh" ""
            "request" "refresh_token"
            "response" "access_token"
            "retries" 1
            "statuses" (vs/jt
              401))
          "name" "apikey"
          "providers" (vs/jt))
        "optspec" (vs/jm)
        "strict" false
        "transport" "wrap")
      "test" (vs/jm
        "options" (vs/jm
          "active" false)
        "optspec" (vs/jm
          "entity" "`$MAP`"
          "net" "`$MAP`")
        "strict" false
        "transport" "base")
      "timeout" (vs/jm
        "options" (vs/jm
          "active" false
          "ms" 30000)
        "optspec" (vs/jm
          "clearTimer" "`$FUNCTION`"
          "setTimer" "`$FUNCTION`")
        "strict" false
        "transport" "wrap"))
    "main" (vs/jm
      "name" "VoxgigSolardemo"
      "slug" "voxgig-solardemo"
      "target" "clojure"
      "version" "0.1.0")
    "options" (vs/jm
      "base" "http://localhost:8901"
      "entity" (vs/jm
        "moon" (vs/jm)
        "planet" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))

(def feature-plugins
  {})

(def feature-extra
  {"secrets" (fn [] (sdk.feature.secrets/secrets-feature (get feature-plugins "secrets")))})
