;; Solardemo SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "moon" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "diameter"
            "req" true
            "type" "`$NUMBER`")
          (vs/jm
            "name" "id"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "kind"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "planet_id"
            "req" true
            "type" "`$STRING`"))
        "name" "moon"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "planet_id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/api/planet/{planet_id}/moon"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{planet_id}"
                  "moon")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "planet_id")
                  (vs/jm
                    "lit" "moon"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "planet_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "planet_id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/api/planet/{planet_id}/moon"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{planet_id}"
                  "moon")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "planet_id")
                  (vs/jm
                    "lit" "moon"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "planet_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "moon_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "param"
                      "name" "planet_id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/api/planet/{planet_id}/moon/{moon_id}"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{planet_id}"
                  "moon"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "moon_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "planet_id")
                  (vs/jm
                    "lit" "moon")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"
                    "planet_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "moon_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "param"
                      "name" "planet_id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "DELETE"
                "orig" "/api/planet/{planet_id}/moon/{moon_id}"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{planet_id}"
                  "moon"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "moon_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "planet_id")
                  (vs/jm
                    "lit" "moon")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"
                    "planet_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "update" (vs/jm
            "input" "data"
            "name" "update"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "moon_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "param"
                      "name" "planet_id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "PUT"
                "orig" "/api/planet/{planet_id}/moon/{moon_id}"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{planet_id}"
                  "moon"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "moon_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "planet_id")
                  (vs/jm
                    "lit" "moon")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"
                    "planet_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "planet"))))
      "planet" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "diameter"
            "req" true
            "type" "`$NUMBER`")
          (vs/jm
            "name" "forbid"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "id"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "kind"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "ok"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "start"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "state"
            "type" "`$STRING`")
          (vs/jm
            "name" "stop"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "why"
            "type" "`$STRING`"))
        "name" "planet"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/api/planet/{planet_id}/forbid"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{id}"
                  "forbid")
                "rename" (vs/jm
                  "param" (vs/jm
                    "planet_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "id")
                  (vs/jm
                    "lit" "forbid"))
                "select" (vs/jm
                  "$action" "forbid"
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/api/planet/{planet_id}/terraform"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{id}"
                  "terraform")
                "rename" (vs/jm
                  "param" (vs/jm
                    "planet_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "id")
                  (vs/jm
                    "lit" "terraform"))
                "select" (vs/jm
                  "$action" "terraform"
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/api/planet"
                "parts" (vs/jt
                  "api"
                  "planet")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet"))
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/api/planet"
                "parts" (vs/jt
                  "api"
                  "planet")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet"))
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/api/planet/{planet_id}"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "planet_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "DELETE"
                "orig" "/api/planet/{planet_id}"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "planet_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "update" (vs/jm
            "input" "data"
            "name" "update"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "PUT"
                "orig" "/api/planet/{planet_id}"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "planet_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt))))
    "feature" (vs/jm
      "test" (vs/jm
        "options" (vs/jm
          "active" false)
        "transport" "base"))
    "main" (vs/jm
      "name" "Solardemo"
      "slug" "solardemo"
      "target" "clojure"
      "version" "0.1.0")
    "options" (vs/jm
      "base" "http://localhost:8901"
      "entity" (vs/jm
        "moon" (vs/jm)
        "planet" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))
