;; Solardemo SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "moon" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "format" "float"
            "name" "diameter"
            "req" true
            "type" "`$NUMBER`")
          (vs/jm
            "name" "id"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "kind"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "planet_id"
            "req" true
            "type" "`$STRING`"))
        "name" "moon"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "planet_id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "contract" (vs/jm
                  "id" "POST /api/planet/{planet_id}/moon"
                  "json" "{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"planet_id\":{\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"planet_id\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"required\":true},\"responses\":{\"201\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"planet_id\":{\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"planet_id\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"description\":\"Created\"}},\"securitySource\":\"unspecified\"}"
                  "source" "openapi3"
                  "version" 1)
                "kind" "http"
                "method" "POST"
                "orig" "/api/planet/{planet_id}/moon"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{planet_id}"
                  "moon")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "planet_id")
                  (vs/jm
                    "lit" "moon"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "planet_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "planet_id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "contract" (vs/jm
                  "id" "GET /api/planet/{planet_id}/moon"
                  "json" "{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"responses\":{\"200\":{\"content\":{\"application/json\":{\"schema\":{\"items\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"planet_id\":{\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"planet_id\",\"kind\",\"diameter\"],\"type\":\"object\"},\"type\":\"array\"}}},\"description\":\"OK\"}},\"securitySource\":\"unspecified\"}"
                  "source" "openapi3"
                  "version" 1)
                "kind" "http"
                "method" "GET"
                "orig" "/api/planet/{planet_id}/moon"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{planet_id}"
                  "moon")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "planet_id")
                  (vs/jm
                    "lit" "moon"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "planet_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "moon_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "param"
                      "name" "planet_id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "contract" (vs/jm
                  "id" "GET /api/planet/{planet_id}/moon/{moon_id}"
                  "json" "{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}},{\"in\":\"path\",\"name\":\"moon_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"responses\":{\"200\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"planet_id\":{\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"planet_id\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"description\":\"OK\"}},\"securitySource\":\"unspecified\"}"
                  "source" "openapi3"
                  "version" 1)
                "kind" "http"
                "method" "GET"
                "orig" "/api/planet/{planet_id}/moon/{moon_id}"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{planet_id}"
                  "moon"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "moon_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "planet_id")
                  (vs/jm
                    "lit" "moon")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"
                    "planet_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "moon_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "param"
                      "name" "planet_id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "contract" (vs/jm
                  "id" "DELETE /api/planet/{planet_id}/moon/{moon_id}"
                  "json" "{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}},{\"in\":\"path\",\"name\":\"moon_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"responses\":{\"204\":{\"description\":\"No Content\"}},\"securitySource\":\"unspecified\"}"
                  "source" "openapi3"
                  "version" 1)
                "kind" "http"
                "method" "DELETE"
                "orig" "/api/planet/{planet_id}/moon/{moon_id}"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{planet_id}"
                  "moon"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "moon_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "planet_id")
                  (vs/jm
                    "lit" "moon")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"
                    "planet_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "update" (vs/jm
            "input" "data"
            "name" "update"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "moon_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "param"
                      "name" "planet_id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "contract" (vs/jm
                  "id" "PUT /api/planet/{planet_id}/moon/{moon_id}"
                  "json" "{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}},{\"in\":\"path\",\"name\":\"moon_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"planet_id\":{\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"planet_id\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"required\":true},\"responses\":{\"200\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"planet_id\":{\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"planet_id\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"description\":\"OK\"}},\"securitySource\":\"unspecified\"}"
                  "source" "openapi3"
                  "version" 1)
                "kind" "http"
                "method" "PUT"
                "orig" "/api/planet/{planet_id}/moon/{moon_id}"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{planet_id}"
                  "moon"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "moon_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "planet_id")
                  (vs/jm
                    "lit" "moon")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"
                    "planet_id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "planet"))))
      "planet" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "format" "float"
            "name" "diameter"
            "req" true
            "type" "`$NUMBER`")
          (vs/jm
            "name" "forbidReason"
            "readOnly" true
            "short" "Why the planet is forbidden, carried from the forbid action's `why`."
            "type" "`$STRING`")
          (vs/jm
            "name" "forbidState"
            "readOnly" true
            "short" "Set by the forbid action, and absent until it first runs."
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "kind"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "terraformState"
            "readOnly" true
            "short" "Set by the terraform action, and absent until it first runs."
            "type" "`$STRING`"))
        "name" "planet"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "contract" (vs/jm
                  "id" "POST /api/planet/{planet_id}/forbid"
                  "json" "{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"forbid\":{\"type\":\"boolean\"},\"why\":{\"type\":\"string\"}},\"type\":\"object\"}}},\"required\":true},\"responses\":{\"200\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"ok\":{\"type\":\"boolean\"},\"state\":{\"type\":\"string\"}},\"type\":\"object\"}}},\"description\":\"OK\"}},\"securitySource\":\"unspecified\"}"
                  "source" "openapi3"
                  "version" 1)
                "kind" "http"
                "method" "POST"
                "orig" "/api/planet/{planet_id}/forbid"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{id}"
                  "forbid")
                "rename" (vs/jm
                  "param" (vs/jm
                    "planet_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "id")
                  (vs/jm
                    "lit" "forbid"))
                "select" (vs/jm
                  "$action" "forbid"
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "contract" (vs/jm
                  "id" "POST /api/planet/{planet_id}/terraform"
                  "json" "{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"start\":{\"type\":\"boolean\"},\"stop\":{\"type\":\"boolean\"}},\"type\":\"object\"}}},\"required\":true},\"responses\":{\"200\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"ok\":{\"type\":\"boolean\"},\"state\":{\"type\":\"string\"}},\"type\":\"object\"}}},\"description\":\"OK\"}},\"securitySource\":\"unspecified\"}"
                  "source" "openapi3"
                  "version" 1)
                "kind" "http"
                "method" "POST"
                "orig" "/api/planet/{planet_id}/terraform"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{id}"
                  "terraform")
                "rename" (vs/jm
                  "param" (vs/jm
                    "planet_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "id")
                  (vs/jm
                    "lit" "terraform"))
                "select" (vs/jm
                  "$action" "terraform"
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm)
                "contract" (vs/jm
                  "id" "POST /api/planet"
                  "json" "{\"parameters\":[],\"protocol\":\"http\",\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"forbidReason\":{\"description\":\"Why the planet is forbidden, carried from the forbid action's `why`. Absent while the planet is allowed.\",\"readOnly\":true,\"type\":\"string\"},\"forbidState\":{\"description\":\"Set by the forbid action, and absent until it first runs. One of allowed or forbidden.\",\"readOnly\":true,\"type\":\"string\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"terraformState\":{\"description\":\"Set by the terraform action, and absent until it first runs. One of idle, terraforming or complete.\",\"readOnly\":true,\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"required\":true},\"responses\":{\"201\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"forbidReason\":{\"description\":\"Why the planet is forbidden, carried from the forbid action's `why`. Absent while the planet is allowed.\",\"readOnly\":true,\"type\":\"string\"},\"forbidState\":{\"description\":\"Set by the forbid action, and absent until it first runs. One of allowed or forbidden.\",\"readOnly\":true,\"type\":\"string\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"terraformState\":{\"description\":\"Set by the terraform action, and absent until it first runs. One of idle, terraforming or complete.\",\"readOnly\":true,\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"description\":\"Created\"}},\"securitySource\":\"unspecified\"}"
                  "source" "openapi3"
                  "version" 1)
                "kind" "http"
                "method" "POST"
                "orig" "/api/planet"
                "parts" (vs/jt
                  "api"
                  "planet")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet"))
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "contract" (vs/jm
                  "id" "GET /api/planet"
                  "json" "{\"parameters\":[],\"protocol\":\"http\",\"responses\":{\"200\":{\"content\":{\"application/json\":{\"schema\":{\"items\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"forbidReason\":{\"description\":\"Why the planet is forbidden, carried from the forbid action's `why`. Absent while the planet is allowed.\",\"readOnly\":true,\"type\":\"string\"},\"forbidState\":{\"description\":\"Set by the forbid action, and absent until it first runs. One of allowed or forbidden.\",\"readOnly\":true,\"type\":\"string\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"terraformState\":{\"description\":\"Set by the terraform action, and absent until it first runs. One of idle, terraforming or complete.\",\"readOnly\":true,\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"kind\",\"diameter\"],\"type\":\"object\"},\"type\":\"array\"}}},\"description\":\"OK\"}},\"securitySource\":\"unspecified\"}"
                  "source" "openapi3"
                  "version" 1)
                "kind" "http"
                "method" "GET"
                "orig" "/api/planet"
                "parts" (vs/jt
                  "api"
                  "planet")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet"))
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "contract" (vs/jm
                  "id" "GET /api/planet/{planet_id}"
                  "json" "{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"responses\":{\"200\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"forbidReason\":{\"description\":\"Why the planet is forbidden, carried from the forbid action's `why`. Absent while the planet is allowed.\",\"readOnly\":true,\"type\":\"string\"},\"forbidState\":{\"description\":\"Set by the forbid action, and absent until it first runs. One of allowed or forbidden.\",\"readOnly\":true,\"type\":\"string\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"terraformState\":{\"description\":\"Set by the terraform action, and absent until it first runs. One of idle, terraforming or complete.\",\"readOnly\":true,\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"description\":\"OK\"}},\"securitySource\":\"unspecified\"}"
                  "source" "openapi3"
                  "version" 1)
                "kind" "http"
                "method" "GET"
                "orig" "/api/planet/{planet_id}"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "planet_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "contract" (vs/jm
                  "id" "DELETE /api/planet/{planet_id}"
                  "json" "{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"responses\":{\"204\":{\"description\":\"No Content\"}},\"securitySource\":\"unspecified\"}"
                  "source" "openapi3"
                  "version" 1)
                "kind" "http"
                "method" "DELETE"
                "orig" "/api/planet/{planet_id}"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "planet_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "update" (vs/jm
            "input" "data"
            "name" "update"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "planet_id"
                      "reqd" true
                      "type" "`$STRING`")))
                "contract" (vs/jm
                  "id" "PUT /api/planet/{planet_id}"
                  "json" "{\"parameters\":[{\"in\":\"path\",\"name\":\"planet_id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"forbidReason\":{\"description\":\"Why the planet is forbidden, carried from the forbid action's `why`. Absent while the planet is allowed.\",\"readOnly\":true,\"type\":\"string\"},\"forbidState\":{\"description\":\"Set by the forbid action, and absent until it first runs. One of allowed or forbidden.\",\"readOnly\":true,\"type\":\"string\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"terraformState\":{\"description\":\"Set by the terraform action, and absent until it first runs. One of idle, terraforming or complete.\",\"readOnly\":true,\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"required\":true},\"responses\":{\"200\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"diameter\":{\"format\":\"float\",\"type\":\"number\"},\"forbidReason\":{\"description\":\"Why the planet is forbidden, carried from the forbid action's `why`. Absent while the planet is allowed.\",\"readOnly\":true,\"type\":\"string\"},\"forbidState\":{\"description\":\"Set by the forbid action, and absent until it first runs. One of allowed or forbidden.\",\"readOnly\":true,\"type\":\"string\"},\"id\":{\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"terraformState\":{\"description\":\"Set by the terraform action, and absent until it first runs. One of idle, terraforming or complete.\",\"readOnly\":true,\"type\":\"string\"}},\"required\":[\"id\",\"name\",\"kind\",\"diameter\"],\"type\":\"object\"}}},\"description\":\"OK\"}},\"securitySource\":\"unspecified\"}"
                  "source" "openapi3"
                  "version" 1)
                "kind" "http"
                "method" "PUT"
                "orig" "/api/planet/{planet_id}"
                "parts" (vs/jt
                  "api"
                  "planet"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "planet_id" "id"))
                "segments" (vs/jt
                  (vs/jm
                    "lit" "api")
                  (vs/jm
                    "lit" "planet")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt))))
    "feature" (vs/jm
      "test" (vs/jm
        "options" (vs/jm
          "active" false)
        "transport" "base"))
    "main" (vs/jm
      "name" "Solardemo"
      "slug" "solardemo"
      "target" "clojure"
      "version" "0.1.0")
    "options" (vs/jm
      "base" "http://localhost:8901"
      "entity" (vs/jm
        "moon" (vs/jm)
        "planet" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))
